"""Tests for the CHStone staging fix and the ablation knobs that sit on top of it.

Three layers, deliberately:

*unit*
    :mod:`c2hlsc_agent.chstone_staging` rewrites two files the converter emits
    (``tb/testbench.cpp`` and ``Makefile``) by pattern. If ``testgen``/``hls_project`` ever
    change their output, the rewrites must degrade to "not applied" rather than silently
    produce something subtly wrong, so every rewrite is tested for both the hit and the miss.

*integration, with a real toolchain*
    A synthetic benchmark that reproduces the exact C89 constructs that block CHStone --
    K&R parameter definitions, a tentative definition redeclared at file scope, an ``int``
    array initialised from unsigned literals, and a file-scope global the candidate also
    defines -- is pushed through the *real* converter, staged, built and run. Then the
    candidate is mutated and the same test must go red. Skipped when gcc/g++/objcopy/make
    are unavailable; never faked.

*arm bookkeeping*
    The knobs an ablation is read from (``--repair-rounds`` vs ``--max-iterations``,
    ``--legacy-staging``) and the reachable-vs-passed accounting, because an arm whose
    configuration is misrecorded produces a table nobody can trust.
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from c2hlsc_agent import chstone_staging  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "run_chstone_staging_driver", SCRIPTS_DIR / "run_chstone.py"
)
assert _spec and _spec.loader
driver = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = driver
_spec.loader.exec_module(driver)

TOP = "chstone_main"
HAVE_TOOLCHAIN = all(shutil.which(tool) for tool in ("gcc", "g++", "objcopy", "make"))


# --------------------------------------------------------------------------- #
# testbench rewrite
# --------------------------------------------------------------------------- #

#: Exactly what c2hlsc_agent.testgen emits for a nullary int top.
TESTBENCH = textwrap.dedent(
    """\
    // Generated by c2hlsc_agent. This file is testbench-only code.
    #include <iostream>

    extern "C" {
    #define restrict __restrict__
    #define chstone_main chstone_main_ref
    #include "../input.c"
    #undef chstone_main
    }

    #include "../src/hls_top.hpp"

    int main() {
      for (int test_idx = 0; test_idx < 100; ++test_idx) {

        int ref_ret = chstone_main_ref();
        int hls_ret = chstone_main();
      }
      std::cout << "c2hlsc_agent: all 100 tests passed, seed=1\\n";
      return 0;
    }
    """
)


class RewriteTestbenchTest(unittest.TestCase):
    def test_replaces_inlined_golden_with_a_declaration(self) -> None:
        new_text, changed = chstone_staging.rewrite_testbench(TESTBENCH, TOP)
        self.assertTrue(changed)
        self.assertNotIn('#include "../input.c"', new_text)
        self.assertIn('extern "C" int chstone_main_ref(void);', new_text)
        # The call site and the rest of the testbench are untouched: the oracle did not
        # change, only how it is built.
        self.assertIn("int ref_ret = chstone_main_ref();", new_text)
        self.assertIn("int hls_ret = chstone_main();", new_text)
        self.assertIn("all 100 tests passed", new_text)

    def test_declaration_uses_the_return_type_the_testbench_actually_calls_with(self) -> None:
        text = TESTBENCH.replace("int ref_ret", "long ref_ret").replace("int hls_ret", "long hls_ret")
        new_text, changed = chstone_staging.rewrite_testbench(text, TOP)
        self.assertTrue(changed)
        self.assertIn('extern "C" long chstone_main_ref(void);', new_text)

    def test_refuses_a_top_that_takes_arguments(self) -> None:
        # This staging links a single nullary symbol. A top with arguments is not a CHStone
        # top, and guessing a signature here would produce a link that compiles and lies.
        text = TESTBENCH.replace("chstone_main_ref();", "chstone_main_ref(ref_a, 3);")
        _, changed = chstone_staging.rewrite_testbench(text, TOP)
        self.assertFalse(changed)

    def test_refuses_when_the_expected_block_is_absent(self) -> None:
        text = TESTBENCH.replace('#include "../input.c"', '#include "../somewhere_else.c"')
        new_text, changed = chstone_staging.rewrite_testbench(text, TOP)
        self.assertFalse(changed)
        self.assertEqual(new_text, text)

    def test_ignores_an_unrelated_extern_c_block(self) -> None:
        text = TESTBENCH.replace(
            'extern "C" {\n#define restrict',
            'extern "C" {\nvoid unrelated(void);\n}\n\nextern "C" {\n#define restrict',
        )
        new_text, changed = chstone_staging.rewrite_testbench(text, TOP)
        self.assertTrue(changed)
        self.assertIn("void unrelated(void);", new_text)
        self.assertNotIn('#include "../input.c"', new_text)


# --------------------------------------------------------------------------- #
# Makefile rewrite
# --------------------------------------------------------------------------- #


class RewriteMakefileTest(unittest.TestCase):
    def setUp(self) -> None:
        from c2hlsc_agent.config import AgentConfig
        from c2hlsc_agent.hls_project import render_makefile

        # The real Makefile, so a change in hls_project.render_makefile fails this test
        # instead of silently disabling the staging in production.
        self.makefile = render_makefile(AgentConfig())

    def test_links_a_separately_compiled_golden_object(self) -> None:
        new_text, changed = chstone_staging.rewrite_makefile(self.makefile, TOP, relax_narrowing=False)
        self.assertTrue(changed)
        self.assertIn("$(CC) $(GOLDEN_CFLAGS) -c golden_ref.c -o $(GOLDEN_OBJ)", new_text)
        self.assertIn("--keep-global-symbol=$(GOLDEN_EXPORT)", new_text)
        self.assertIn("GOLDEN_EXPORT ?= chstone_main_ref", new_text)
        # The testbench binary now links the golden object instead of compiling input.c.
        self.assertIn(
            "$(CXX) $(CXXFLAGS) tb/testbench.cpp src/hls_top.cpp $(GOLDEN_OBJ) -o $(TB_EXE)",
            new_text,
        )
        self.assertIn("mutation-check:", new_text)
        self.assertNotIn(
            "$(CXX) $(CXXFLAGS) tb/testbench.cpp src/hls_top.cpp -o $(TB_EXE)", new_text
        )

    def test_narrowing_relaxation_is_opt_out_and_documented(self) -> None:
        relaxed, _ = chstone_staging.rewrite_makefile(self.makefile, TOP, relax_narrowing=True)
        strict, _ = chstone_staging.rewrite_makefile(self.makefile, TOP, relax_narrowing=False)
        self.assertIn("CXXFLAGS += -Wno-narrowing", relaxed)
        self.assertIn(chstone_staging.narrowing_relaxation_note(), relaxed)
        self.assertNotIn("-Wno-narrowing", strict)

    def test_refuses_when_the_rule_is_absent(self) -> None:
        text = self.makefile.replace("$(TB_EXE): tb/testbench.cpp", "$(TB_EXE): tb/other.cpp")
        new_text, changed = chstone_staging.rewrite_makefile(text, TOP, relax_narrowing=True)
        self.assertFalse(changed)
        self.assertEqual(new_text, text)


# --------------------------------------------------------------------------- #
# mutant source
# --------------------------------------------------------------------------- #


class MutantSourceTest(unittest.TestCase):
    def test_wraps_the_top_and_perturbs_the_returned_value(self) -> None:
        candidate = '#include "hls_top.hpp"\n\nint chstone_main() {\n  return 0;\n}\n'
        source, changed = chstone_staging.render_mutant_source(candidate, TOP)
        self.assertTrue(changed)
        self.assertIn("int chstone_main_c2hlsc_premutation() {", source)
        self.assertIn("int chstone_main() { return chstone_main_c2hlsc_premutation() + 1; }", source)

    def test_leaves_the_repair_agents_rename_directives_alone(self) -> None:
        # The repair agent renames the top before #including the original sources. Rewriting
        # those two directives would let input.c define chstone_main at global scope and the
        # mutant would fail to link -- which the harness would then have to score as
        # inconclusive, losing the evidence.
        candidate = textwrap.dedent(
            """\
            #include "hls_top.hpp"
            #define chstone_main chstone_main_c2hlsc_repair_reference
            #include "../input.c"
            #undef chstone_main

            int chstone_main() { return chstone_main_c2hlsc_repair_reference(); }
            """
        )
        source, changed = chstone_staging.render_mutant_source(candidate, TOP)
        self.assertTrue(changed)
        self.assertIn("#define chstone_main chstone_main_c2hlsc_repair_reference", source)
        self.assertIn("#undef chstone_main", source)
        self.assertIn("int chstone_main() { return chstone_main_c2hlsc_premutation() + 1; }", source)

    def test_reports_no_change_when_the_top_is_absent(self) -> None:
        source, changed = chstone_staging.render_mutant_source("int other() { return 0; }\n", TOP)
        self.assertFalse(changed)
        self.assertNotIn("premutation", source)

    def test_write_mutant_source_returns_none_without_a_candidate(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            self.assertIsNone(chstone_staging.write_mutant_source(Path(tmp), TOP))


# --------------------------------------------------------------------------- #
# sibling staging and the whole-project entry point
# --------------------------------------------------------------------------- #


def _fake_project(root: Path) -> Path:
    from c2hlsc_agent.config import AgentConfig
    from c2hlsc_agent.hls_project import render_makefile

    project = root / "project"
    (project / "tb").mkdir(parents=True)
    (project / "src").mkdir()
    (project / "input.c").write_text("int chstone_main(void) { return 0; }\n", encoding="utf-8")
    (project / "tb" / "testbench.cpp").write_text(TESTBENCH, encoding="utf-8")
    (project / "Makefile").write_text(render_makefile(AgentConfig()), encoding="utf-8")
    (project / "src" / "hls_top.cpp").write_text("int chstone_main() { return 0; }\n", encoding="utf-8")
    return project


class StageProjectTest(unittest.TestCase):
    def test_stages_siblings_without_clobbering_or_copying_the_top(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "bench"
            source.mkdir()
            (source / "top.c").write_text("top\n", encoding="utf-8")
            (source / "helper.c").write_text("helper\n", encoding="utf-8")
            (source / "hls.tcl").write_text("tcl\n", encoding="utf-8")
            (source / "keep.h").write_text("fresh\n", encoding="utf-8")
            project = root / "project"
            project.mkdir()
            (project / "keep.h").write_text("already staged\n", encoding="utf-8")

            copied = chstone_staging.stage_sibling_sources(project, source, "top.c")

            self.assertEqual(copied, ["helper.c"])
            self.assertFalse((project / "top.c").exists())
            self.assertFalse((project / "hls.tcl").exists())
            self.assertEqual((project / "keep.h").read_text(encoding="utf-8"), "already staged\n")

    def test_end_to_end_rewrites_and_is_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "bench"
            source.mkdir()
            (source / "top.c").write_text("top\n", encoding="utf-8")
            project = _fake_project(root)

            first = chstone_staging.stage_project(project, source, "top.c", TOP)
            self.assertTrue(first.applied)
            self.assertEqual(first.golden_export, "chstone_main_ref")
            golden = (project / "golden_ref.c").read_text(encoding="utf-8")
            self.assertIn("#define chstone_main chstone_main_ref", golden)
            self.assertIn('#include "input.c"', golden)

            tb_after_first = (project / "tb" / "testbench.cpp").read_text(encoding="utf-8")
            mk_after_first = (project / "Makefile").read_text(encoding="utf-8")

            second = chstone_staging.stage_project(project, source, "top.c", TOP)
            self.assertTrue(second.applied)
            self.assertEqual(
                (project / "tb" / "testbench.cpp").read_text(encoding="utf-8"), tb_after_first
            )
            self.assertEqual((project / "Makefile").read_text(encoding="utf-8"), mk_after_first)

    def test_reports_why_it_declined_instead_of_half_applying(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "bench"
            source.mkdir()
            project = _fake_project(root)
            (project / "tb" / "testbench.cpp").write_text("int main(){return 0;}\n", encoding="utf-8")

            result = chstone_staging.stage_project(project, source, "top.c", TOP)

            self.assertFalse(result.applied)
            self.assertIsNotNone(result.skipped_reason)
            # Declining must not leave a golden_ref.c behind that nothing links.
            self.assertFalse((project / "golden_ref.c").exists())

    def test_missing_project_is_reported_not_raised(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            result = chstone_staging.stage_project(
                Path(tmp) / "nope", Path(tmp), "top.c", TOP
            )
            self.assertFalse(result.applied)
            self.assertIn("missing", (result.skipped_reason or ""))


# --------------------------------------------------------------------------- #
# the -Wno-narrowing justification, checked rather than asserted in prose
# --------------------------------------------------------------------------- #

_NARROWING_SOURCE = """\
unsigned char probe[16] = {0};
int table[4] = {0, 0xffffffff, 0xfffffffe, 0x80000000};
"""


@unittest.skipUnless(HAVE_TOOLCHAIN, "needs gcc/g++/objcopy/make")
class NarrowingRelaxationTest(unittest.TestCase):
    """``-Wno-narrowing`` must be a diagnostic switch, not a codegen switch.

    CHStone initialises ``int`` arrays from unsigned literals. If suppressing the C++
    narrowing diagnostic changed the stored values, the staging would be altering the
    program under test. It does not, and this proves it by comparing the emitted bytes of
    the same initialiser built as C and as C++.
    """

    def _table_bytes(self, tmp: Path, name: str, compiler: str, flags: list[str]) -> bytes:
        source = tmp / name
        source.write_text(_NARROWING_SOURCE, encoding="utf-8")
        obj = tmp / (name + ".o")
        build = subprocess.run(
            [compiler, *flags, "-c", str(source), "-o", str(obj)],
            capture_output=True, text=True,
        )
        self.assertEqual(build.returncode, 0, build.stderr)
        dump = tmp / (name + ".bin")
        subprocess.run(
            ["objcopy", "-O", "binary", "--only-section=.data", str(obj), str(dump)],
            check=True, capture_output=True,
        )
        return dump.read_bytes()

    def test_cpp_narrowing_is_an_error_without_the_flag(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "strict.cpp"
            source.write_text(_NARROWING_SOURCE, encoding="utf-8")
            build = subprocess.run(
                ["g++", "-std=c++17", "-c", str(source), "-o", str(Path(tmp) / "strict.o")],
                capture_output=True, text=True,
            )
            self.assertNotEqual(build.returncode, 0)
            self.assertIn("narrowing", build.stderr)

    def test_relaxed_cpp_emits_the_same_bytes_as_c(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            as_c = self._table_bytes(root, "ref.c", "gcc", ["-O1"])
            as_cpp = self._table_bytes(
                root, "relaxed.cpp", "g++", ["-std=c++17", "-O1", "-Wno-narrowing"]
            )
            self.assertEqual(as_c, as_cpp)
            self.assertTrue(as_c, "expected the initialiser to land in .data")


# --------------------------------------------------------------------------- #
# integration: a synthetic benchmark with every blocking construct
# --------------------------------------------------------------------------- #

#: Reproduces, in ~40 lines, exactly what blocks CHStone under the legacy staging:
#:   * a K&R parameter definition (blowfish, motion)
#:   * a tentative definition redeclared at file scope (jpeg)
#:   * a ``register`` declaration (jpeg)
#:   * an ``int`` table initialised from unsigned literals (adpcm, jpeg)
#:   * a file-scope global the candidate will also define (mips, sha: the collision)
SYNTHETIC_TOP = """\
#include <stdio.h>

int main_result;
int main_result;

int mask_table[4] = {0, 0xffffffff, 0xfffffffe, 0x80000000};

int accumulate ();

int
accumulate (n)
     int n;
{
  register int i;
  int total = 0;
  for (i = 0; i < n; i++)
    total += mask_table[i & 3];
  return total;
}

int
main ()
{
  main_result = 0;
  if (accumulate (8) != -6)
    main_result += 1;
  printf ("%d\\n", main_result);
  return main_result;
}
"""


@unittest.skipUnless(HAVE_TOOLCHAIN, "needs gcc/g++/objcopy/make")
class StagedEquivalenceIntegrationTest(unittest.TestCase):
    """Build a real project through the real converter, stage it, run it, then mutate it.

    This is the test that would catch a false green: if the staged equivalence binary
    passed against a candidate whose returned value is deliberately wrong, the CHStone
    numbers would be meaningless.
    """

    def _build_project(self, root: Path) -> tuple[Path, Path]:
        from c2hlsc_agent.analyze import analyze_source
        from c2hlsc_agent.config import AgentConfig
        from c2hlsc_agent.convert import generate_hls_sources
        from c2hlsc_agent.hls_project import write_project

        source_dir = root / "bench"
        source_dir.mkdir()
        top_file = source_dir / "top.c"
        renamed, count = driver.rename_main(SYNTHETIC_TOP)
        self.assertEqual(count, 1)
        top_file.write_text(renamed, encoding="utf-8")

        config = AgentConfig()
        config.num_tests = 5
        analysis = analyze_source(top_file, TOP, config)
        generated = generate_hls_sources(analysis, config, llm=None)
        project = root / "project"
        write_project(project, analysis, generated, config)
        return source_dir, project

    def test_legacy_staging_cannot_even_build_this(self) -> None:
        # The control: without the fix, the C89 above never reaches a verdict, and the error
        # is in the golden reference the harness inlined -- not in the candidate.
        with tempfile.TemporaryDirectory() as tmp:
            _, project = self._build_project(Path(tmp))
            build = subprocess.run(["make", "test"], cwd=project, capture_output=True, text=True)
            self.assertNotEqual(build.returncode, 0)
            combined = build.stdout + build.stderr
            self.assertIn("error:", combined)
            self.assertIn("tb/../input.c", combined)

    #: A self-contained C++ translation of the same kernel -- the shape the LLM generator
    #: actually emits, and the shape that only becomes measurable once the golden reference
    #: stops being compiled by g++.
    CANDIDATE_CPP = textwrap.dedent(
        """\
        #include "hls_top.hpp"
        #include <cstdio>

        namespace {
        const int kMask[4] = {0, -1, -2, -2147483648};
        int candidate_accumulate(int n) {
          int total = 0;
          for (int i = 0; i < n; ++i) total += kMask[i & 3];
          return total;
        }
        }  // namespace

        int chstone_main() {
          int result = 0;
          if (candidate_accumulate(8) != -6) result += 1;
          std::printf("%d\\n", result);
          return result;
        }
        """
    )

    def test_staged_project_passes_and_the_mutant_goes_red(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source_dir, project = self._build_project(Path(tmp))

            staged = chstone_staging.stage_project(project, source_dir, "top.c", TOP)
            self.assertTrue(staged.applied, staged.skipped_reason)
            (project / "src" / "hls_top.cpp").write_text(self.CANDIDATE_CPP, encoding="utf-8")

            run = subprocess.run(["make", "test"], cwd=project, capture_output=True, text=True)
            combined = run.stdout + run.stderr
            self.assertEqual(run.returncode, 0, combined)
            self.assertIn("all 5 tests passed", combined)
            self.assertEqual(driver._stimulus_count(combined), 5)

            # Exactly one symbol leaves the golden object, so its file-scope state can
            # neither collide with the candidate's nor be silently shared with it. Sharing
            # would be the worse failure: the two sides would agree by construction.
            symbols = subprocess.run(
                ["nm", "--defined-only", "-g", "golden_ref.o"],
                cwd=project, capture_output=True, text=True, check=True,
            ).stdout.split()
            self.assertIn("chstone_main_ref", symbols)
            self.assertNotIn("main_result", symbols)
            self.assertNotIn("mask_table", symbols)

            verdict, detail = driver.run_mutation_check(project, timeout=120)
            self.assertEqual(verdict, "red", detail)
            self.assertIn("Mismatch test=", detail)

    def test_a_candidate_that_reincludes_the_c89_fails_on_its_own_translation_unit(self) -> None:
        # This is blowfish/motion under the staged flow. The staging fixed the golden side,
        # and what is left is the deterministic converter's own strategy -- pulling C89 into
        # a C++ TU -- failing. It must be scored, with the error attributed to src/, not tb/.
        with tempfile.TemporaryDirectory() as tmp:
            source_dir, project = self._build_project(Path(tmp))
            chstone_staging.stage_project(project, source_dir, "top.c", TOP)
            (project / "src" / "hls_top.cpp").write_text(
                '#include "hls_top.hpp"\n'
                f"#define {TOP} {TOP}_c2hlsc_repair_reference\n"
                '#include "../input.c"\n'
                f"#undef {TOP}\n\n"
                f"int {TOP}() {{ return {TOP}_c2hlsc_repair_reference(); }}\n",
                encoding="utf-8",
            )
            run = subprocess.run(["make", "test"], cwd=project, capture_output=True, text=True)
            combined = run.stdout + run.stderr
            self.assertNotEqual(run.returncode, 0)
            self.assertIn("src/../input.c", combined)
            self.assertNotIn("tb/../input.c", combined)
            rung, family = driver._classify_conversion(
                {"software_equivalence": "fail"}, combined
            )
            self.assertEqual((rung, family), ("generated", "candidate_includes_original_c"))

    def test_strict_narrowing_arm_shows_the_flag_is_load_bearing(self) -> None:
        # A candidate whose ONLY C++ problem is a narrowing initialiser: it builds under the
        # default arm and fails under --strict-narrowing. That is the whole cost of the flag,
        # measured rather than asserted.
        candidate = (
            '#include "hls_top.hpp"\n'
            "static const int kMask[4] = {0, 0xffffffff, 0xfffffffe, 0x80000000};\n"
            "int chstone_main() { int t = 0; for (int i = 0; i < 8; ++i) t += kMask[i & 3];"
            " return t != -6; }\n"
        )
        for relax, expect_ok in ((True, True), (False, False)):
            with self.subTest(relax_narrowing=relax), tempfile.TemporaryDirectory() as tmp:
                source_dir, project = self._build_project(Path(tmp))
                chstone_staging.stage_project(
                    project, source_dir, "top.c", TOP, relax_narrowing=relax
                )
                (project / "src" / "hls_top.cpp").write_text(candidate, encoding="utf-8")
                run = subprocess.run(["make", "test"], cwd=project, capture_output=True, text=True)
                combined = run.stdout + run.stderr
                if expect_ok:
                    self.assertEqual(run.returncode, 0, combined)
                    self.assertIn("all 5 tests passed", combined)
                else:
                    self.assertNotEqual(run.returncode, 0)
                    self.assertIn("narrowing", combined)
                    self.assertIn("src/hls_top.cpp", combined)


# --------------------------------------------------------------------------- #
# mutation verdicts
# --------------------------------------------------------------------------- #


class MutationVerdictTest(unittest.TestCase):
    def _check(self, make_result: tuple[int, str], *, mutant: bool = True) -> tuple[str, str]:
        with mock.patch.object(chstone_staging, "write_mutant_source",
                               return_value=Path("src/hls_top_mutant.cpp") if mutant else None), \
             mock.patch.object(driver.chstone_staging, "write_mutant_source",
                               return_value=Path("src/hls_top_mutant.cpp") if mutant else None), \
             mock.patch.object(driver, "_make", return_value=make_result):
            return driver.run_mutation_check(Path("/nonexistent"), timeout=10)

    def test_mismatch_line_is_the_only_thing_that_counts_as_red(self) -> None:
        verdict, detail = self._check((1, "Mismatch test=0 return expected=0 actual=1 seed=1\n"))
        self.assertEqual(verdict, "red")
        self.assertIn("Mismatch test=0", detail)

    def test_a_mutant_that_fails_to_compile_is_inconclusive_not_red(self) -> None:
        # This is the trap: a nonzero exit code from a build failure looks exactly like a
        # caught mutation if you only check the return code.
        verdict, detail = self._check((2, "src/hls_top_mutant.cpp:9:1: error: redefinition\n"))
        self.assertEqual(verdict, "inconclusive")
        self.assertIn("error", detail)

    def test_a_surviving_mutant_is_flagged_as_a_false_green(self) -> None:
        verdict, _ = self._check((0, "c2hlsc_agent: all 100 tests passed, seed=1\n"))
        self.assertEqual(verdict, "FALSE_GREEN")

    def test_unwrappable_candidate_is_inconclusive(self) -> None:
        verdict, detail = self._check((0, ""), mutant=False)
        self.assertEqual(verdict, "inconclusive")
        self.assertIn("could not rename", detail)

    def test_timeout_is_inconclusive(self) -> None:
        verdict, _ = self._check((124, "make mutation-check timed out after 10s"))
        self.assertEqual(verdict, "inconclusive")


# --------------------------------------------------------------------------- #
# ablation arms
# --------------------------------------------------------------------------- #


def _args(**overrides: object) -> argparse.Namespace:
    base = dict(
        native_baseline=False, use_llm=False, llm_backend=None, llm_model=None,
        llm_cli_cmd=None, auto_repair=False, max_iterations=2, repair_rounds=None,
        staged=True, relax_narrowing=True, mutation_check=True, label=None, keep_going=True,
    )
    base.update(overrides)
    return argparse.Namespace(**base)


class RepairRoundsTest(unittest.TestCase):
    def test_max_iterations_keeps_its_cli_meaning(self) -> None:
        # `convert --max-iterations N` is N verification attempts, so N-1 repairs. The
        # default of 2 is what every published CHStone number was measured under; changing
        # this mapping silently would make old and new arms incomparable.
        self.assertEqual(driver.repair_rounds(_args(auto_repair=True, max_iterations=2)), 1)
        self.assertEqual(driver.repair_rounds(_args(auto_repair=True, max_iterations=4)), 3)
        self.assertEqual(driver.repair_rounds(_args(auto_repair=True, max_iterations=1)), 0)
        self.assertEqual(driver.repair_rounds(_args(auto_repair=True, max_iterations=0)), 0)

    def test_repair_rounds_spelling_wins_when_given(self) -> None:
        for rounds in (0, 1, 2, 3):
            self.assertEqual(
                driver.repair_rounds(_args(auto_repair=True, repair_rounds=rounds, max_iterations=99)),
                rounds,
            )

    def test_no_repair_without_auto_repair(self) -> None:
        self.assertEqual(driver.repair_rounds(_args(auto_repair=False, max_iterations=4)), 0)
        self.assertEqual(driver.repair_rounds(_args(auto_repair=False, repair_rounds=3)), 0)

    def test_arm_descriptor_records_what_would_change_the_number(self) -> None:
        arm = driver.arm_descriptor(_args(auto_repair=True, repair_rounds=2, use_llm=True,
                                          llm_model="opus", label="llm_r2"))
        self.assertEqual(arm["label"], "llm_r2")
        self.assertEqual(arm["generator"], "llm")
        self.assertEqual(arm["staging"], "golden_c_tu")
        self.assertEqual(arm["repair_rounds_allowed"], 2)
        legacy = driver.arm_descriptor(_args(staged=False))
        self.assertEqual(legacy["staging"], "legacy_inline")
        # The narrowing relaxation and the mutation check only exist in the staged flow;
        # reporting them as on for a legacy arm would describe a run that did not happen.
        self.assertFalse(legacy["relax_narrowing"])
        self.assertFalse(legacy["mutation_check"])


class MainArgumentValidationTest(unittest.TestCase):
    def test_repair_rounds_implies_auto_repair(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            argv = ["--benchmark", tmp, "--out-dir", tmp, "--repair-rounds", "2"]
            parsed = driver.build_parser().parse_args(argv)
            self.assertFalse(parsed.auto_repair)
            with mock.patch.object(driver, "discover_benchmarks", return_value=[]):
                with self.assertRaises(SystemExit):
                    driver.main(argv)

    def test_native_baseline_refuses_candidate_flags(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(SystemExit) as ctx:
                driver.main(["--benchmark", tmp, "--out-dir", tmp, "--native-baseline", "--use-llm"])
            self.assertIn("constructs no candidate", str(ctx.exception))

    def test_staged_is_the_default_and_legacy_is_explicit(self) -> None:
        parsed = driver.build_parser().parse_args(["--benchmark", ".", "--out-dir", "."])
        self.assertTrue(parsed.staged)
        legacy = driver.build_parser().parse_args(
            ["--benchmark", ".", "--out-dir", ".", "--legacy-staging"]
        )
        self.assertFalse(legacy.staged)


# --------------------------------------------------------------------------- #
# reachable vs passed
# --------------------------------------------------------------------------- #


class ReachabilityAccountingTest(unittest.TestCase):
    def _row(self, name: str, ok: bool, family: str | None) -> object:
        return driver.BenchmarkResult(
            benchmark=name, mode="agent", rung="host_equivalence" if ok else "generated",
            ok=ok, failure_family=family,
        )

    def test_harness_blocked_benchmarks_are_unreachable_not_zeros(self) -> None:
        rows = [
            self._row("aes", True, None),
            self._row("adpcm", False, "original_c_not_valid_cpp"),
            self._row("mips", False, "golden_candidate_symbol_collision"),
            self._row("sha", False, "generated_hlsc_does_not_compile"),
        ]
        summary = driver._summarise(rows, "agent", 1.0, 4, arm={"label": "x"})
        self.assertEqual(summary["passed"], 1)
        self.assertEqual(summary["reachable"], 2)
        self.assertEqual(summary["passed_of_reachable"], 1)
        self.assertEqual(sorted(summary["unreachable"]), ["adpcm", "mips"])

    def test_candidate_side_c89_failure_is_scored_not_excused(self) -> None:
        # The same C89 constructs, but reached through the candidate's own translation unit,
        # are the converter's problem. Folding them into the harness bucket would let the
        # deterministic arm hide its failures behind the staging fix.
        rows = [self._row("motion", False, "candidate_includes_original_c")]
        summary = driver._summarise(rows, "agent", 1.0, 1, arm={})
        self.assertEqual(summary["reachable"], 1)
        self.assertEqual(summary["passed_of_reachable"], 0)
        self.assertEqual(summary["unreachable"], [])


#: conversion_report.json as it looks once host equivalence has actually run and failed.
#: With an empty report the classifier is right to say "analyzed / static_source_rejected":
#: nothing reached the oracle at all.
FAILED_EQUIV_REPORT = {"software_equivalence": "fail"}


class ClassifyConversionTest(unittest.TestCase):
    def test_golden_side_c89_error_is_the_harness_fault(self) -> None:
        log = "tb/../input.c:814:6: error: narrowing conversion of '4294967295'\n"
        self.assertEqual(driver._classify_conversion(FAILED_EQUIV_REPORT, log), ("generated", "original_c_not_valid_cpp"))

    def test_candidate_side_c89_error_is_the_converters_fault(self) -> None:
        log = "src/../bf_cfb64.c:82:1: error: variable or field 'BF_cfb64_encrypt' declared void\n"
        self.assertEqual(
            driver._classify_conversion(FAILED_EQUIV_REPORT, log), ("generated", "candidate_includes_original_c")
        )

    def test_symbol_collision_keeps_its_own_family(self) -> None:
        log = "/usr/bin/ld: multiple definition of `main_result'; first defined here\n"
        self.assertEqual(
            driver._classify_conversion(FAILED_EQUIV_REPORT, log),
            ("generated", "golden_candidate_symbol_collision"),
        )

    def test_pass_banner_wins(self) -> None:
        self.assertEqual(
            driver._classify_conversion({}, "c2hlsc_agent: all 100 tests passed, seed=1\n"),
            ("host_equivalence", None),
        )


class StagedVerdictAuthorityTest(unittest.TestCase):
    """The staged flow must score the STAGED log, never ``conversion_report.json``.

    Phase 1 of the staged flow runs ``convert`` once, which verifies the project *before*
    the staging lands. Its ``conversion_report.json`` therefore describes a different build.
    For most CHStone benchmarks that stale field says "fail" and is harmless, but a
    benchmark that passed unstaged and then fails to link once the real golden object is
    added would be reported green off the stale field. These tests pin that shut.
    """

    def _run(self, make_result: tuple[int, str], report: dict) -> object:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        root = Path(tmp.name)
        source = root / "bench"
        source.mkdir()
        (source / "top.c").write_text(SYNTHETIC_TOP, encoding="utf-8")
        bench = driver.ChstoneBenchmark("synthetic", source, source / "top.c")
        out_dir = root / "out"

        def fake_convert(cmd, **kwargs):
            project = out_dir / "benchmarks" / "synthetic" / "project"
            project.parent.mkdir(parents=True, exist_ok=True)
            _fake_project(project.parent)
            import json as _json
            (project / "conversion_report.json").write_text(_json.dumps(report), encoding="utf-8")
            return subprocess.CompletedProcess(cmd, 0, "", "")

        args = _args(auto_repair=False, repair_rounds=0, mutation_check=False)
        args.timeout = 60
        with mock.patch.object(driver.subprocess, "run", side_effect=fake_convert), \
             mock.patch.object(driver, "_make", return_value=make_result):
            return driver.run_agent_staged(bench, out_dir, args)

    def test_stale_pass_in_the_conversion_report_cannot_make_a_failed_link_green(self) -> None:
        row = self._run(
            (1, "/usr/bin/ld: multiple definition of `main_result'\n"),
            {"software_equivalence": "pass",
             "phases": {"software_equivalence": {"name": "software_equivalence", "status": "pass"}}},
        )
        self.assertFalse(row.ok)
        self.assertEqual(row.rung, "generated")
        self.assertEqual(row.failure_family, "golden_candidate_symbol_collision")
        self.assertIsNone(row.stimulus_count)

    def test_a_real_pass_records_the_stimulus_count_it_reported(self) -> None:
        row = self._run(
            (0, "c2hlsc_agent: all 100 tests passed, seed=1\n"),
            {"software_equivalence": "fail"},
        )
        self.assertTrue(row.ok)
        self.assertEqual(row.rung, "host_equivalence")
        self.assertEqual(row.stimulus_count, 100)
        self.assertEqual(row.staging, "golden_c_tu")
        self.assertEqual(row.repair_rounds_allowed, 0)


class StimulusCountTest(unittest.TestCase):
    def test_reads_the_count_the_testbench_reported(self) -> None:
        self.assertEqual(
            driver._stimulus_count("c2hlsc_agent: all 100 tests passed, seed=1"), 100
        )
        self.assertIsNone(driver._stimulus_count("boom"))


if __name__ == "__main__":
    unittest.main()
