from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from c2hlsc_agent import llm as llm_module
from c2hlsc_agent.llm import OpenAICompatibleLLMClient, resolve_backend

from c2hlsc_agent.analyze import analyze_source
from c2hlsc_agent.config import AgentConfig
from c2hlsc_agent.convert import generate_hls_sources
from c2hlsc_agent.equivalence import PhaseResult, VerificationState
from c2hlsc_agent.hls_project import write_project
from c2hlsc_agent.hlsc_repair_agent import load_repair_audit, repair_project
from c2hlsc_agent.llm import (
    build_llm_client,
    extract_code_blocks,
    extract_full_file,
    extract_hls_source,
    is_plausible_translation_unit,
    missing_llm_reason,
)


VECTOR_ADD = """#include <stdint.h>

void vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {
  for (int i = 0; i < n; ++i) {
    out[i] = a[i] + b[i];
  }
}
"""


class FakeLLM:
    """Deterministic in-memory stand-in for the Anthropic client (no network)."""

    def __init__(self, response: str, model: str = "fake-model") -> None:
        self.response = response
        self.model = model
        self.calls: list[tuple[str, str]] = []

    def complete(self, system: str, user: str, *, max_tokens: int = 8000) -> str:
        self.calls.append((system, user))
        return self.response


def _write_source(tmp: Path, name: str = "input.c", text: str = VECTOR_ADD) -> Path:
    path = tmp / name
    path.write_text(text, encoding="utf-8")
    return path


def _analyze(tmp: Path, config: AgentConfig):
    source = _write_source(tmp)
    config.input_files = [source]
    config.top = "vector_add"
    return analyze_source(source, "vector_add", config)


GENERATOR_RESPONSE = """1. Assumptions
- Vitis HLS target.

3. Original code
```c
void vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {
  for (int i = 0; i < n; ++i) { out[i] = a[i] + b[i]; }
}
```

4. Vitis HLS annotated code
```cpp
// LLM-GENERATED
#include "hls_top.hpp"

void vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {
#pragma HLS PIPELINE
  for (int i = 0; i < n; ++i) {
    out[i] = a[i] + b[i];
  }
}
```

5. Expected hardware impact
- Pipelined loop.
"""


class LlmGeneratorTests(unittest.TestCase):
    def test_generator_uses_llm_output_when_enabled(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True)
            analysis = _analyze(tmp, config)
            fake = FakeLLM(GENERATOR_RESPONSE)
            generated = generate_hls_sources(analysis, config, llm=fake)
            self.assertIn("// LLM-GENERATED", generated.source)
            self.assertIn('#include "hls_top.hpp"', generated.source)
            self.assertEqual(len(fake.calls), 1)
            self.assertTrue(any("LLM HLS-C generator" in t for t in generated.transformations))

    def test_generator_falls_back_without_client(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True)
            analysis = _analyze(tmp, config)
            generated = generate_hls_sources(analysis, config, llm=None)
            self.assertIn("Generated by c2hlsc_agent.", generated.source)
            self.assertNotIn("// LLM-GENERATED", generated.source)

    def test_generator_falls_back_on_unparsable_output(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True)
            analysis = _analyze(tmp, config)
            fake = FakeLLM("I could not produce code for this function.")
            generated = generate_hls_sources(analysis, config, llm=fake)
            self.assertIn("Generated by c2hlsc_agent.", generated.source)
            self.assertTrue(any("fell back to the conservative" in t for t in generated.transformations))

    def test_generator_ignored_when_use_llm_false(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=False)
            analysis = _analyze(tmp, config)
            fake = FakeLLM(GENERATOR_RESPONSE)
            generated = generate_hls_sources(analysis, config, llm=fake)
            self.assertNotIn("// LLM-GENERATED", generated.source)
            self.assertEqual(fake.calls, [])


REPAIR_RESPONSE = """Here is the corrected file:
```cpp
// LLM-REPAIRED
#include "hls_top.hpp"

void vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {
  for (int i = 0; i < n; ++i) {
    out[i] = a[i] + b[i];
  }
}
```
"""


def _csynth_failure_state() -> VerificationState:
    state = VerificationState()
    state.add_phase(PhaseResult("software_equivalence", "pass"))
    state.add_phase(PhaseResult("csim", "pass"))
    state.add_phase(PhaseResult("csynth", "fail", summary="synthesis error: cannot schedule loop"))
    state.add_phase(PhaseResult("cosim", "blocked", summary="csynth failed"))
    return state


class LlmRepairTests(unittest.TestCase):
    def _project(self, tmp: Path, config: AgentConfig):
        analysis = _analyze(tmp, config)
        generated = generate_hls_sources(analysis, config)
        out = tmp / "build"
        write_project(out, analysis, generated, config)
        return analysis, out

    def test_llm_repair_patches_generated_hls_when_mechanical_fails(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True, run_vitis=True)
            analysis, out = self._project(tmp, config)
            fake = FakeLLM(REPAIR_RESPONSE)
            outcome = repair_project(out, analysis, config, _csynth_failure_state(), 1, llm=fake)
            self.assertEqual(outcome.status, "applied_llm")
            self.assertTrue(outcome.changed)
            self.assertEqual(len(fake.calls), 1)
            patched = (out / "src" / "hls_top.cpp").read_text(encoding="utf-8")
            self.assertIn("// LLM-REPAIRED", patched)
            audit = load_repair_audit(out)
            self.assertTrue(audit)
            self.assertEqual(audit[-1].status, "applied_llm")
            self.assertIn("src/hls_top.cpp", audit[-1].target_files)

    def test_no_llm_leaves_mechanical_no_change(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True, run_vitis=True)
            analysis, out = self._project(tmp, config)
            outcome = repair_project(out, analysis, config, _csynth_failure_state(), 1, llm=None)
            self.assertEqual(outcome.status, "no_change")
            self.assertFalse(outcome.changed)
            self.assertNotIn("// LLM-REPAIRED", (out / "src" / "hls_top.cpp").read_text(encoding="utf-8"))

    def test_llm_repair_never_touches_the_oracle_testbench(self):
        # Even when the failure is routed to a testbench/C-semantics scope, the LLM repair
        # must only rewrite src/hls_top.cpp; the host-equivalence oracle is never sent or changed.
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True, run_vitis=False)
            analysis, out = self._project(tmp, config)
            tb_before = (out / "tb" / "testbench.cpp").read_text(encoding="utf-8")
            state = VerificationState()
            state.add_phase(
                PhaseResult("software_equivalence", "fail", summary="compile error: undefined reference to foo")
            )
            fake = FakeLLM(REPAIR_RESPONSE)
            outcome = repair_project(out, analysis, config, state, 1, llm=fake)
            self.assertEqual(outcome.status, "applied_llm")
            self.assertEqual(outcome.target_files, ("src/hls_top.cpp",))
            self.assertEqual((out / "tb" / "testbench.cpp").read_text(encoding="utf-8"), tb_before)
            self.assertIn("// LLM-REPAIRED", (out / "src" / "hls_top.cpp").read_text(encoding="utf-8"))

    def test_llm_repair_rejects_prose_response(self):
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(use_llm=True, run_vitis=True)
            analysis, out = self._project(tmp, config)
            before = (out / "src" / "hls_top.cpp").read_text(encoding="utf-8")
            prose = "The vector_add( ) kernel cannot be scheduled; consider pipelining."
            fake = FakeLLM(f"Here is my analysis:\n```text\n{prose}\n```\n")
            outcome = repair_project(out, analysis, config, _csynth_failure_state(), 1, llm=fake)
            self.assertEqual(outcome.status, "no_change")
            self.assertFalse(outcome.changed)
            self.assertEqual((out / "src" / "hls_top.cpp").read_text(encoding="utf-8"), before)


class LlmHelperTests(unittest.TestCase):
    def test_extract_hls_source_prefers_annotated_block(self):
        source = extract_hls_source(GENERATOR_RESPONSE, "vector_add", VECTOR_ADD)
        self.assertIsNotNone(source)
        self.assertIn("// LLM-GENERATED", source)

    def test_extract_hls_source_returns_none_without_definition(self):
        self.assertIsNone(extract_hls_source("no code here", "vector_add", VECTOR_ADD))

    def test_extract_hls_source_adds_header_include(self):
        text = "```cpp\nvoid vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {}\n```"
        source = extract_hls_source(text, "vector_add", VECTOR_ADD)
        self.assertIsNotNone(source)
        self.assertIn('#include "hls_top.hpp"', source)

    def test_extract_full_file_picks_longest_matching_block(self):
        text = "```cpp\nshort()\n```\n```cpp\nint main() { return 0; }\n```"
        body = extract_full_file(text, must_contain="int main")
        self.assertIsNotNone(body)
        self.assertIn("int main", body)

    def test_extract_full_file_skips_prose_block(self):
        # A long ```text block mentioning the marker must not beat the real ```cpp block.
        prose = "int main " * 50
        text = f"```text\n{prose}\n```\n```cpp\nint main() {{ return 0; }}\n```"
        body = extract_full_file(text, must_contain="int main")
        self.assertIsNotNone(body)
        self.assertIn("return 0;", body)
        self.assertNotIn("int main int main", body)

    def test_extract_full_file_none_when_only_prose(self):
        text = "```text\nthis mentions int main but is not code\n```"
        self.assertIsNone(extract_full_file(text, must_contain="int main"))

    def test_extract_hls_source_skips_echoed_original_after_marker(self):
        response = (
            "4. Vitis HLS annotated code\n"
            "For reference, the original:\n"
            "```cpp\n"
            "void vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {\n"
            "  for (int i = 0; i < n; ++i) { out[i] = a[i] + b[i]; }\n"
            "}\n"
            "```\n"
            "Optimized:\n"
            "```cpp\n"
            "// PIPELINED\n"
            "void vector_add(const int32_t *a, const int32_t *b, int32_t *out, int n) {\n"
            "#pragma HLS PIPELINE\n"
            "  for (int i = 0; i < n; ++i) { out[i] = a[i] + b[i]; }\n"
            "}\n"
            "```\n"
        )
        source = extract_hls_source(response, "vector_add", VECTOR_ADD)
        self.assertIsNotNone(source)
        self.assertIn("// PIPELINED", source)

    def test_extract_hls_source_rejects_unbalanced_braces(self):
        text = "```cpp\nvoid vector_add(const int32_t *a) {\n  // truncated, no closing brace\n```"
        self.assertIsNone(extract_hls_source(text, "vector_add", VECTOR_ADD))

    def test_extract_code_blocks_handles_nested_four_backtick_fence(self):
        nested = "````cpp\nvoid foo() {\n  /* sample: ```c int q; ``` */\n  return 0;\n}\n````"
        blocks = extract_code_blocks(nested)
        self.assertEqual(len(blocks), 1)
        lang, body = blocks[0]
        self.assertEqual(lang, "cpp")
        self.assertIn("return 0;", body)
        self.assertIn("int q;", body)

    def test_is_plausible_translation_unit(self):
        self.assertTrue(is_plausible_translation_unit("void vector_add(int *a) { (void)a; }", "vector_add"))
        self.assertFalse(is_plausible_translation_unit("void vector_add(int *a) {", "vector_add"))
        self.assertFalse(is_plausible_translation_unit("not code at all", "vector_add"))

    def test_build_llm_client_none_when_disabled(self):
        self.assertIsNone(build_llm_client(AgentConfig(use_llm=False)))
        self.assertEqual(missing_llm_reason(AgentConfig(use_llm=False)), "LLM not requested (pass --use-llm)")

    def test_build_llm_client_none_without_credentials(self):
        # With no backend configured and no credentials/base-url in the env, auto resolves
        # to 'none' and the client is None even if use_llm is requested.
        with mock.patch.dict("os.environ", {}, clear=False):
            import os

            for var in (
                "ANTHROPIC_API_KEY",
                "ANTHROPIC_AUTH_TOKEN",
                "OPENAI_API_KEY",
                "OPENAI_BASE_URL",
                "C2HLSC_LLM_BASE_URL",
                "C2HLSC_LLM_API_KEY",
                "C2HLSC_LLM_MODEL",
            ):
                os.environ.pop(var, None)
            self.assertEqual(resolve_backend(AgentConfig(use_llm=True)), "none")
            self.assertIsNone(build_llm_client(AgentConfig(use_llm=True)))

    def test_build_llm_client_openai_backend_local(self):
        # A local OpenAI-compatible endpoint needs no key; constructing the client makes
        # no network call.
        config = AgentConfig(
            use_llm=True,
            llm_backend="openai",
            llm_base_url="http://localhost:11434/v1",
            llm_model="qwen2.5-coder",
        )
        client = build_llm_client(config)
        self.assertIsInstance(client, OpenAICompatibleLLMClient)
        self.assertEqual(client.model, "qwen2.5-coder")
        self.assertEqual(client.base_url, "http://localhost:11434/v1")
        self.assertIsNone(missing_llm_reason(config))

    def test_resolve_backend_auto_prefers_base_url(self):
        self.assertEqual(
            resolve_backend(AgentConfig(use_llm=True, llm_base_url="http://localhost:11434/v1")),
            "openai",
        )
        self.assertEqual(resolve_backend(AgentConfig(use_llm=True, llm_backend="none")), "none")

    def test_openai_client_builds_request_and_parses_content(self):
        captured: dict = {}

        class _FakeResp:
            def __init__(self, payload: dict) -> None:
                self._payload = json.dumps(payload).encode("utf-8")

            def read(self) -> bytes:
                return self._payload

            def __enter__(self):
                return self

            def __exit__(self, *exc):
                return False

        def fake_urlopen(request, timeout=0):
            captured["url"] = request.full_url
            captured["method"] = request.get_method()
            captured["body"] = json.loads(request.data.decode("utf-8"))
            return _FakeResp({"choices": [{"message": {"content": "// LOCAL-MODEL\nvoid foo() {}"}}]})

        with mock.patch.object(llm_module.urllib.request, "urlopen", fake_urlopen):
            client = OpenAICompatibleLLMClient("http://localhost:11434/v1/", "qwen", api_key=None)
            out = client.complete("system text", "user text", max_tokens=128)

        self.assertIn("// LOCAL-MODEL", out)
        self.assertEqual(captured["url"], "http://localhost:11434/v1/chat/completions")
        self.assertEqual(captured["method"], "POST")
        self.assertEqual(captured["body"]["model"], "qwen")
        self.assertEqual(captured["body"]["max_tokens"], 128)
        self.assertEqual(captured["body"]["messages"][0]["role"], "system")
        self.assertEqual(captured["body"]["messages"][1]["content"], "user text")

    def test_openai_local_backend_drives_generator_end_to_end(self):
        # The generator uses whatever backend build_llm_client returns; here a mocked
        # local OpenAI-compatible server returns the synthesizable unit.
        with tempfile.TemporaryDirectory() as raw:
            tmp = Path(raw)
            config = AgentConfig(
                use_llm=True,
                llm_backend="openai",
                llm_base_url="http://localhost:11434/v1",
                llm_model="qwen2.5-coder",
            )
            analysis = _analyze(tmp, config)
            client = build_llm_client(config)
            self.assertIsInstance(client, OpenAICompatibleLLMClient)

            class _FakeResp:
                def __init__(self, payload: dict) -> None:
                    self._payload = json.dumps(payload).encode("utf-8")

                def read(self) -> bytes:
                    return self._payload

                def __enter__(self):
                    return self

                def __exit__(self, *exc):
                    return False

            def fake_urlopen(request, timeout=0):
                return _FakeResp({"choices": [{"message": {"content": GENERATOR_RESPONSE}}]})

            from c2hlsc_agent.convert import generate_hls_sources

            with mock.patch.object(llm_module.urllib.request, "urlopen", fake_urlopen):
                generated = generate_hls_sources(analysis, config, llm=client)
            self.assertIn("// LLM-GENERATED", generated.source)


if __name__ == "__main__":
    unittest.main()
