from __future__ import annotations

from dataclasses import dataclass, field

from .analyze import AnalysisResult, FunctionArg
from .closure import ClosureResult, extract_closure
from .config import AgentConfig
from .hlsc_generator import HLSC_GENERATOR_PROMPT_ID, HLSC_GENERATOR_SYSTEM_PROMPT
from .llm import (
    LLMClient,
    build_generator_user_prompt,
    build_nl_reference_prompt,
    extract_hls_source,
    extract_reference_c,
)


@dataclass
class GeneratedSource:
    header: str
    source: str
    transformations: list[str] = field(default_factory=list)
    interface_pragmas: list[dict[str, str]] = field(default_factory=list)
    generator_prompt_id: str = HLSC_GENERATOR_PROMPT_ID
    closure: ClosureResult | None = None
    """What was hoisted to make the emitted TU self-contained; None when unavailable."""


def _include_for_types(args: list[FunctionArg], return_type: str) -> str:
    """The baseline include set, used when closure extraction is unavailable.

    This alone is not enough for any kernel that names a type of its own -- see
    :mod:`c2hlsc_agent.closure` for why, and for what replaces it when libclang is
    installed.
    """

    text = " ".join([return_type] + [arg.c_type for arg in args])
    includes = ["#include <stdint.h>"]
    if "ap_int" in text or "ap_uint" in text:
        includes.append("#include <ap_int.h>")
    return "\n".join(includes)


def _closure_for(analysis: AnalysisResult, config: AgentConfig) -> ClosureResult:
    """Compute the file-scope context the top closes over.

    Returns an unavailable result (empty preamble) when libclang is missing, so the
    caller falls back to the previous behaviour rather than emitting a TU that silently
    lost its context.
    """

    defines = tuple(
        flag[2:] for flag in getattr(config, "compiler_flags", []) if flag.startswith("-D")
    )
    include_dirs = tuple(str(path) for path in getattr(config, "include_dirs", []))
    extra = tuple(
        flag for flag in getattr(config, "compiler_flags", []) if not flag.startswith("-D")
    )
    try:
        return extract_closure(
            analysis.function.source_path,
            analysis.function.name,
            include_dirs=include_dirs,
            defines=defines,
            extra_args=extra,
        )
    except Exception as exc:  # noqa: BLE001 - closure extraction must never fail conversion
        return ClosureResult(available=False, diagnostics=[f"closure extraction failed: {exc}"])


def _pragma_lines(config: AgentConfig, args: list[FunctionArg]) -> tuple[list[str], list[dict[str, str]]]:
    if not config.allow_pragmas:
        return [], []
    lines: list[str] = []
    rows: list[dict[str, str]] = []
    if config.interface_mode == "default":
        return lines, rows
    for arg in args:
        if config.interface_mode == "s_axilite" or not arg.is_pointer_like:
            line = f"#pragma HLS INTERFACE s_axilite port={arg.name}"
            reason = "scalar/control interface requested by configuration"
        elif config.interface_mode in {"ap_memory", "m_axi", "axis"}:
            mode = config.interface_mode
            line = f"#pragma HLS INTERFACE {mode} port={arg.name}"
            reason = f"{mode} interface requested by configuration; direction is {arg.direction}"
        else:
            continue
        lines.append(line)
        rows.append({"argument": arg.name, "pragma": line, "reason": reason})
    lines.append("#pragma HLS INTERFACE s_axilite port=return")
    rows.append({"argument": "return", "pragma": lines[-1], "reason": "control return interface requested by configuration"})
    return lines, rows


def _generate_conservative_sources(analysis: AnalysisResult, config: AgentConfig) -> GeneratedSource:
    function = analysis.function
    pragma_lines, pragma_rows = _pragma_lines(config, function.args)
    body = function.body.rstrip()
    if pragma_lines:
        body = "\n" + "\n".join(f"  {line}" for line in pragma_lines) + "\n" + body
    closure = _closure_for(analysis, config)

    # The header must be able to name the types in its own signature, and the source must
    # be able to name everything the body closes over. Both come from the closure; the
    # bare include list is only the fallback for when libclang is unavailable.
    header_context = closure.type_preamble if closure.available and closure.type_preamble else (
        _include_for_types(function.args, function.return_type)
    )
    source_context = closure.definition_preamble if closure.available else ""

    header = f"""#ifndef C2HLSC_GENERATED_HLS_TOP_HPP
#define C2HLSC_GENERATED_HLS_TOP_HPP

{header_context}

{function.signature};

#endif
"""
    source = f"""// Generated by c2hlsc_agent.
// Transformation policy: preserve the original top-function control/data flow unless
// a conservative, equivalence-preserving refactor is explicitly recorded.

#include "hls_top.hpp"
{source_context}
// --- generated top ---
{function.return_type} {function.name}({', '.join(arg.raw for arg in function.args)}) {{
{body}
}}
"""
    transformations = [
        f"Applied {HLSC_GENERATOR_PROMPT_ID} as the HLS-C generator policy.",
        "Preserved original top-function body and signature for equivalence-first HLS baseline.",
    ]
    if closure.available and closure.preamble:
        transformations.append(
            f"Hoisted the top's file-scope closure ({len(closure.symbols)} symbols, "
            f"{len(closure.macros)} macros) so the emitted translation unit is self-contained."
        )
        transformations.extend(f"Normalized C to C++: {note}." for note in closure.normalizations[:20])
        if len(closure.normalizations) > 20:
            transformations.append(
                f"Normalized C to C++: {len(closure.normalizations) - 20} further rewrites (see closure report)."
            )
    elif not closure.available:
        transformations.append(
            "Closure extraction unavailable ("
            + "; ".join(closure.diagnostics[:1])
            + "); emitted the bare include list, so the TU carries no file-scope context."
        )
    return GeneratedSource(
        header=header,
        source=source,
        transformations=transformations,
        interface_pragmas=pragma_rows,
        closure=closure,
    )


def _llm_candidate(
    analysis: AnalysisResult,
    config: AgentConfig,
    llm: LLMClient,
    conservative: GeneratedSource,
    attempt: int = 0,
) -> GeneratedSource | None:
    """One LLM generation attempt, or ``None`` when unavailable/unparsable."""

    model = getattr(llm, "model", "?")
    try:
        original_source = analysis.function.source_path.read_text(encoding="utf-8")
        user = build_generator_user_prompt(analysis, original_source, nl_spec=getattr(config, "nl_spec", None))
        if attempt:
            user += (
                f"\nThis is independent candidate #{attempt + 1}: take a different pragma/refactoring "
                "strategy than the most obvious one, while preserving equivalence."
            )
        response = llm.complete(HLSC_GENERATOR_SYSTEM_PROMPT, user)
        source = extract_hls_source(response, analysis.function.name, original_source)
    except Exception as exc:
        # Surface the concrete backend failure (main's diagnostic improvement). This note
        # only survives when every candidate fails and the conservative copy is returned.
        conservative.transformations.append(
            f"LLM generation attempt {attempt + 1} failed [{type(exc).__name__}: {exc}]."
        )
        return None
    if not source:
        return None
    return GeneratedSource(
        header=conservative.header,
        source=source,
        transformations=[
            f"LLM HLS-C generator (model={model}, policy={HLSC_GENERATOR_PROMPT_ID}, candidate={attempt + 1}) "
            "produced a synthesizable translation unit."
            + (" User NL design intent was included in the prompt." if getattr(config, "nl_spec", None) else ""),
            "Verifier-gated: output is checked by host equivalence and Vitis CSim/CSynth/CoSim; "
            "failures trigger repair or fall back to the conservative copy.",
        ],
        interface_pragmas=[],
    )


def generate_hls_sources(
    analysis: AnalysisResult,
    config: AgentConfig,
    llm: LLMClient | None = None,
) -> GeneratedSource:
    """Generate HLS-C sources.

    When an LLM client is supplied and ``config.use_llm`` is set, the generator asks
    the model (following the ``hlsc_generator_vitis_beginner_v1`` policy) for a
    synthesizable translation unit and uses it in place of the verbatim copy. The
    conservative deterministic source is always built first and used as the fallback if
    the LLM is unavailable or its output cannot be parsed, so behaviour stays safe and
    the verifier remains the equivalence gate. ``config.nl_spec`` (user natural-language
    design intent) is included in the generator prompt when present.
    """

    conservative = _generate_conservative_sources(analysis, config)
    if llm is None or not getattr(config, "use_llm", False):
        return conservative

    candidate = _llm_candidate(analysis, config, llm, conservative)
    if candidate is None:
        # _llm_candidate records the specific failure reason (from main) on conservative.
        conservative.transformations.append(
            f"LLM HLS-C generation requested (model={getattr(llm, 'model', '?')}) but unavailable or "
            "unparsable; fell back to the conservative top-function copy."
        )
        return conservative
    return candidate


def generate_hls_source_candidates(
    analysis: AnalysisResult,
    config: AgentConfig,
    llm: LLMClient,
    count: int,
) -> list[GeneratedSource]:
    """Generate up to ``count`` independent LLM candidates (structural-gate filtered)."""

    conservative = _generate_conservative_sources(analysis, config)
    candidates: list[GeneratedSource] = []
    seen: set[str] = set()
    for attempt in range(max(1, count)):
        candidate = _llm_candidate(analysis, config, llm, conservative, attempt=attempt)
        if candidate is None:
            continue
        key = "".join(candidate.source.split())
        if key in seen:
            continue
        seen.add(key)
        candidates.append(candidate)
    return candidates


class ReferenceGenerationError(RuntimeError):
    """The LLM backend call for the NL golden reference failed (not just unparsable)."""


def generate_reference_c(nl_spec: str, top_name: str, llm: LLMClient) -> str | None:
    """NL-only mode: generate the plain-C golden reference implementation.

    The result becomes ``input.c`` — the equivalence oracle the generated testbench and
    the whole verifier ladder compare against — so the rest of the pipeline runs exactly
    as in the C-input modes. Returns ``None`` when the model answered but the output is
    unparsable; raises :class:`ReferenceGenerationError` when the backend CALL itself
    failed (CLI error, timeout, auth/HTTP error) so the caller can report the real cause
    instead of blaming the model's answer.
    """

    system, user = build_nl_reference_prompt(nl_spec, top_name)
    try:
        response = llm.complete(system, user)
    except Exception as exc:  # noqa: BLE001 — surface the backend failure with context
        raise ReferenceGenerationError(str(exc)) from exc
    return extract_reference_c(response, top_name)
