from __future__ import annotations

from dataclasses import dataclass, field

from .analyze import AnalysisResult, FunctionArg
from .config import AgentConfig


@dataclass
class GeneratedSource:
    header: str
    source: str
    transformations: list[str] = field(default_factory=list)
    interface_pragmas: list[dict[str, str]] = field(default_factory=list)


def _include_for_types(args: list[FunctionArg], return_type: str) -> str:
    text = " ".join([return_type] + [arg.c_type for arg in args])
    includes = ["#include <stdint.h>"]
    if "ap_int" in text or "ap_uint" in text:
        includes.append("#include <ap_int.h>")
    return "\n".join(includes)


def _pragma_lines(config: AgentConfig, args: list[FunctionArg]) -> tuple[list[str], list[dict[str, str]]]:
    if not config.allow_pragmas:
        return [], []
    lines: list[str] = []
    rows: list[dict[str, str]] = []
    if config.interface_mode == "default":
        return lines, rows
    for arg in args:
        if config.interface_mode == "s_axilite" or not arg.is_pointer_like:
            line = f"#pragma HLS INTERFACE s_axilite port={arg.name}"
            reason = "scalar/control interface requested by configuration"
        elif config.interface_mode in {"ap_memory", "m_axi", "axis"}:
            mode = config.interface_mode
            line = f"#pragma HLS INTERFACE {mode} port={arg.name}"
            reason = f"{mode} interface requested by configuration; direction is {arg.direction}"
        else:
            continue
        lines.append(line)
        rows.append({"argument": arg.name, "pragma": line, "reason": reason})
    lines.append("#pragma HLS INTERFACE s_axilite port=return")
    rows.append({"argument": "return", "pragma": lines[-1], "reason": "control return interface requested by configuration"})
    return lines, rows


def generate_hls_sources(analysis: AnalysisResult, config: AgentConfig) -> GeneratedSource:
    function = analysis.function
    pragma_lines, pragma_rows = _pragma_lines(config, function.args)
    body = function.body.rstrip()
    if pragma_lines:
        body = "\n" + "\n".join(f"  {line}" for line in pragma_lines) + "\n" + body
    header = f"""#ifndef C2HLSC_GENERATED_HLS_TOP_HPP
#define C2HLSC_GENERATED_HLS_TOP_HPP

{_include_for_types(function.args, function.return_type)}

{function.signature};

#endif
"""
    source = f"""// Generated by c2hlsc_agent.
// Transformation policy: preserve the original top-function control/data flow unless
// a conservative, equivalence-preserving refactor is explicitly recorded.

#include "hls_top.hpp"

{function.return_type} {function.name}({', '.join(arg.raw for arg in function.args)}) {{
{body}
}}
"""
    return GeneratedSource(
        header=header,
        source=source,
        transformations=["Preserved original top-function body and signature for equivalence-first HLS baseline."],
        interface_pragmas=pragma_rows,
    )
