from __future__ import annotations

from dataclasses import dataclass, field

from .analyze import AnalysisResult, FunctionArg
from .config import AgentConfig
from .hlsc_generator import HLSC_GENERATOR_PROMPT_ID, HLSC_GENERATOR_SYSTEM_PROMPT
from .llm import LLMClient, build_generator_user_prompt, extract_hls_source


@dataclass
class GeneratedSource:
    header: str
    source: str
    transformations: list[str] = field(default_factory=list)
    interface_pragmas: list[dict[str, str]] = field(default_factory=list)
    generator_prompt_id: str = HLSC_GENERATOR_PROMPT_ID


def _include_for_types(args: list[FunctionArg], return_type: str) -> str:
    text = " ".join([return_type] + [arg.c_type for arg in args])
    includes = ["#include <stdint.h>"]
    if "ap_int" in text or "ap_uint" in text:
        includes.append("#include <ap_int.h>")
    return "\n".join(includes)


def _pragma_lines(config: AgentConfig, args: list[FunctionArg]) -> tuple[list[str], list[dict[str, str]]]:
    if not config.allow_pragmas:
        return [], []
    lines: list[str] = []
    rows: list[dict[str, str]] = []
    if config.interface_mode == "default":
        return lines, rows
    for arg in args:
        if config.interface_mode == "s_axilite" or not arg.is_pointer_like:
            line = f"#pragma HLS INTERFACE s_axilite port={arg.name}"
            reason = "scalar/control interface requested by configuration"
        elif config.interface_mode in {"ap_memory", "m_axi", "axis"}:
            mode = config.interface_mode
            line = f"#pragma HLS INTERFACE {mode} port={arg.name}"
            reason = f"{mode} interface requested by configuration; direction is {arg.direction}"
        else:
            continue
        lines.append(line)
        rows.append({"argument": arg.name, "pragma": line, "reason": reason})
    lines.append("#pragma HLS INTERFACE s_axilite port=return")
    rows.append({"argument": "return", "pragma": lines[-1], "reason": "control return interface requested by configuration"})
    return lines, rows


def _generate_conservative_sources(analysis: AnalysisResult, config: AgentConfig) -> GeneratedSource:
    function = analysis.function
    pragma_lines, pragma_rows = _pragma_lines(config, function.args)
    body = function.body.rstrip()
    if pragma_lines:
        body = "\n" + "\n".join(f"  {line}" for line in pragma_lines) + "\n" + body
    header = f"""#ifndef C2HLSC_GENERATED_HLS_TOP_HPP
#define C2HLSC_GENERATED_HLS_TOP_HPP

{_include_for_types(function.args, function.return_type)}

{function.signature};

#endif
"""
    source = f"""// Generated by c2hlsc_agent.
// Transformation policy: preserve the original top-function control/data flow unless
// a conservative, equivalence-preserving refactor is explicitly recorded.

#include "hls_top.hpp"

{function.return_type} {function.name}({', '.join(arg.raw for arg in function.args)}) {{
{body}
}}
"""
    return GeneratedSource(
        header=header,
        source=source,
        transformations=[
            f"Applied {HLSC_GENERATOR_PROMPT_ID} as the HLS-C generator policy.",
            "Preserved original top-function body and signature for equivalence-first HLS baseline.",
        ],
        interface_pragmas=pragma_rows,
    )


def generate_hls_sources(
    analysis: AnalysisResult,
    config: AgentConfig,
    llm: LLMClient | None = None,
) -> GeneratedSource:
    """Generate HLS-C sources.

    When an LLM client is supplied and ``config.use_llm`` is set, the generator asks
    the model (following the ``hlsc_generator_vitis_beginner_v1`` policy) for a
    synthesizable translation unit and uses it in place of the verbatim copy. The
    conservative deterministic source is always built first and used as the fallback if
    the LLM is unavailable or its output cannot be parsed, so behaviour stays safe and
    the verifier remains the equivalence gate.
    """

    conservative = _generate_conservative_sources(analysis, config)
    if llm is None or not getattr(config, "use_llm", False):
        return conservative

    model = getattr(llm, "model", "?")
    try:
        original_source = analysis.function.source_path.read_text(encoding="utf-8")
        response = llm.complete(
            HLSC_GENERATOR_SYSTEM_PROMPT,
            build_generator_user_prompt(analysis, original_source),
        )
        source = extract_hls_source(response, analysis.function.name, original_source)
    except Exception:
        source = None

    if not source:
        conservative.transformations.append(
            f"LLM HLS-C generation requested (model={model}) but unavailable or unparsable; "
            "fell back to the conservative top-function copy."
        )
        return conservative

    return GeneratedSource(
        header=conservative.header,
        source=source,
        transformations=[
            f"LLM HLS-C generator (model={model}, policy={HLSC_GENERATOR_PROMPT_ID}) produced a "
            "synthesizable translation unit.",
            "Verifier-gated: output is checked by host equivalence and Vitis CSim/CSynth/CoSim; "
            "failures trigger repair or fall back to the conservative copy.",
        ],
        interface_pragmas=[],
    )
