from __future__ import annotations

import os
import re
import shutil
import stat
from dataclasses import dataclass
from pathlib import Path

from .analyze import AnalysisResult
from .config import AgentConfig
from .convert import GeneratedSource
from .leveri_testgen import generate_leveri_testbenches
from .testgen import generate_testbench
from .verilog_testgen import generate_verilog_testbenches


@dataclass
class ProjectFiles:
    root: Path
    generated_files: list[Path]


_QUOTED_INCLUDE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*"([^"]+)"', re.M)


def _stage_generated_header_dependencies(
    out_dir: Path, source_path: Path, header: str, include_dirs: list[Path]
) -> list[Path]:
    """Copy the local headers named by the generated API into the project tree."""

    copied: list[Path] = []
    seen: set[Path] = set()

    def stage(include_name: str, search_dirs: list[Path], relative_name: Path) -> None:
        if relative_name.is_absolute() or ".." in relative_name.parts:
            return
        source = next(
            (Path(directory) / include_name for directory in search_dirs if (Path(directory) / include_name).is_file()),
            None,
        )
        if source is None:
            return
        resolved = source.resolve()
        if resolved in seen:
            return
        seen.add(resolved)
        destination = out_dir / relative_name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        copied.append(destination)
        text = source.read_text(encoding="utf-8", errors="replace")
        for nested in _QUOTED_INCLUDE.findall(text):
            stage(nested, [source.parent, *include_dirs], relative_name.parent / nested)

    for include_name in _QUOTED_INCLUDE.findall(header):
        stage(include_name, [source_path.parent, *include_dirs], Path(include_name))
    return copied


def _tcl_path(value: object) -> str:
    r"""Render a path for a Tcl double-quoted string.

    A Windows path is a minefield inside Tcl quotes: a path such as
    C:\\Users\\luke\\bench\\rosetta contains \\b (backspace) and \\r (carriage return),
    so it silently becomes "C:Userslukeench" plus a line break -- which also breaks the
    surrounding quoting and leaves Vitis reporting `Invalid attribute value`. Forward
    slashes are accepted by both Tcl and Vitis on Windows and carry no escape meaning.
    """

    return str(value).replace("\\", "/")


def _vitis_cflags(config: AgentConfig, *, for_testbench: bool = False) -> str:
    """`-cflags` for add_files: the project's own headers plus the configured flags.

    Vitis compiles CSim from a nested build directory, so the project root and `src` have
    to be named explicitly or a quoted include in the generated header cannot be found.
    """

    # `file normalize` is evaluated by Tcl when the script runs, from the project root, so
    # these become absolute. Relative includes do not survive: Vitis runs the CoSim TB
    # preprocess from a different working directory than CSim, and `-I.` then points
    # somewhere else entirely.
    flags = ["-I[file normalize .]", "-I[file normalize src]"]
    for item in getattr(config, "include_dirs", []):
        flags.append(f"-I{_tcl_path(item)}")
    forced_include = False
    for flag in getattr(config, "compiler_flags", []):
        text = _tcl_path(flag)
        # `-include x` is two argv entries. They exist to make the *original* source
        # compile on a modern libstdc++; Vitis synthesis has no such header search path and
        # rejects them outright, and the generated design no longer needs them because the
        # closure states its own includes. Keep them for the testbench, which still
        # compiles the original.
        if not for_testbench:
            if text == "-include":
                forced_include = True
                continue
            if forced_include:
                forced_include = False
                continue
        flags.append(text)
    return " ".join(flags)


def render_run_hls(analysis: AnalysisResult, config: AgentConfig) -> str:
    fn = analysis.function
    cosim = f"cosim_design -rtl {config.rtl}"
    if config.cosim_tool:
        cosim = f"cosim_design -tool {config.cosim_tool} -rtl {config.rtl}"
    cflags = _vitis_cflags(config)
    tb_cflags = _vitis_cflags(config, for_testbench=True)
    return f"""# Generated by c2hlsc_agent.
open_project c2hlsc_project
set_top {fn.name}
add_files src/hls_top.cpp -cflags "{cflags}"
add_files -tb tb/testbench.cpp -cflags "{tb_cflags}"
open_solution "solution1" -flow_target vivado
set_part {{{config.part}}}
create_clock -period {config.clock} -name default
csim_design
csynth_design
{cosim}
exit
"""


def render_run_csim(analysis: AnalysisResult, config: AgentConfig) -> str:
    fn = analysis.function
    cflags = _vitis_cflags(config)
    tb_cflags = _vitis_cflags(config, for_testbench=True)
    return f"""# Generated by c2hlsc_agent.
open_project -reset c2hlsc_project
set_top {fn.name}
add_files src/hls_top.cpp -cflags "{cflags}"
add_files -tb tb/testbench.cpp -cflags "{tb_cflags}"
open_solution "solution1" -flow_target vivado
set_part {{{config.part}}}
create_clock -period {config.clock} -name default
csim_design
exit
"""


def render_run_csynth() -> str:
    return """# Generated by c2hlsc_agent.
open_project c2hlsc_project
open_solution "solution1"
csynth_design
exit
"""


def render_run_cosim(config: AgentConfig) -> str:
    cosim = f"cosim_design -rtl {config.rtl}"
    if config.cosim_tool:
        cosim = f"cosim_design -tool {config.cosim_tool} -rtl {config.rtl}"
    return f"""# Generated by c2hlsc_agent.
open_project c2hlsc_project
open_solution "solution1"
{cosim}
exit
"""


def render_makefile(config: AgentConfig) -> str:
    flags = " ".join(config.compiler_flags)
    return f"""CXX ?= g++
CXXFLAGS ?= -std=c++17 -Wall -Wextra -I src -I . {flags}
TB_EXE ?= c2hlsc_tb
LEVERI_GOLDEN_EXE ?= leveri_golden_tb
LEVERI_HLS_EXE ?= leveri_hls_tb
RTL_VECTORS_EXE ?= rtl_vectors_tb

.PHONY: all test leveri-test gcov-coverage klee-coverage coverage \\
        rtl-vectors rtl-testbench rtl-cosim clean vitis

all: test

$(TB_EXE): tb/testbench.cpp src/hls_top.cpp src/hls_top.hpp input.c
\t$(CXX) $(CXXFLAGS) tb/testbench.cpp src/hls_top.cpp -o $(TB_EXE)

$(LEVERI_GOLDEN_EXE): tb/leveri_golden_tb.cpp input.c
\t$(CXX) $(CXXFLAGS) tb/leveri_golden_tb.cpp -o $(LEVERI_GOLDEN_EXE)

$(LEVERI_HLS_EXE): tb/leveri_hls_tb.cpp src/hls_top.cpp src/hls_top.hpp
\t$(CXX) $(CXXFLAGS) tb/leveri_hls_tb.cpp src/hls_top.cpp -o $(LEVERI_HLS_EXE)

test: $(TB_EXE)
\t./$(TB_EXE)

leveri-test: $(LEVERI_GOLDEN_EXE) $(LEVERI_HLS_EXE)
\t./$(LEVERI_GOLDEN_EXE)
\t./$(LEVERI_HLS_EXE)
\tpython3 tb/leveri_compare.py leveri_golden_trace.csv leveri_hls_trace.csv

gcov-coverage:
\tpython3 tb/run_gcov.py

klee-coverage:
\tpython3 tb/run_klee.py

coverage: gcov-coverage klee-coverage

# Standalone RTL (Verilog) testbench flow. Produces golden expected vectors from the
# original C, renders a self-checking testbench, and (post-synthesis) simulates the RTL.
$(RTL_VECTORS_EXE): tb/rtl_vectors_tb.cpp input.c
\t$(CXX) $(CXXFLAGS) tb/rtl_vectors_tb.cpp -o $(RTL_VECTORS_EXE)

rtl-vectors: $(RTL_VECTORS_EXE)
\tmkdir -p rtl_vectors
\t./$(RTL_VECTORS_EXE)

rtl-testbench:
\tpython3 tb/gen_rtl_tb.py --from-contract

rtl-cosim:
\tpython3 tb/run_rtl_sim.py

vitis:
\tvitis_hls -f run_hls.tcl

clean:
\trm -f $(TB_EXE) $(LEVERI_GOLDEN_EXE) $(LEVERI_HLS_EXE) $(RTL_VECTORS_EXE)
\trm -f leveri_golden_trace.csv leveri_hls_trace.csv
\trm -rf coverage rtl_vectors
\trm -f tb/*_tb.sv
\trm -f *.gcda *.gcno *.gcov
\trm -rf c2hlsc_project
"""


def render_run_all() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail
make test
if command -v vitis_hls >/dev/null 2>&1; then
  vitis_hls -f run_hls.tcl
else
  echo "vitis_hls not found; host equivalence completed, Vitis phases skipped." >&2
fi
"""


def write_project(out_dir: Path, analysis: AnalysisResult, generated: GeneratedSource, config: AgentConfig) -> ProjectFiles:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "src").mkdir(exist_ok=True)
    (out_dir / "tb").mkdir(exist_ok=True)
    leveri_bundle = generate_leveri_testbenches(analysis, config)
    verilog_bundle = generate_verilog_testbenches(analysis, config)
    shutil.copyfile(analysis.function.source_path, out_dir / "input.c")
    files = [
        out_dir / "input.c",
        out_dir / "src" / "hls_top.hpp",
        out_dir / "src" / "hls_top.cpp",
        out_dir / "tb" / "testbench.cpp",
        out_dir / "tb" / "leveri_golden_tb.cpp",
        out_dir / "tb" / "leveri_hls_tb.cpp",
        out_dir / "tb" / "leveri_compare.py",
        out_dir / "tb" / "run_gcov.py",
        out_dir / "tb" / "klee_driver.cpp",
        out_dir / "tb" / "run_klee.py",
        out_dir / "tb" / "leveri_manifest.json",
        out_dir / "tb" / "rtl_vectors_tb.cpp",
        out_dir / "tb" / "gen_rtl_tb.py",
        out_dir / "tb" / "run_rtl_sim.py",
        out_dir / "tb" / "rtl_tb_manifest.json",
        out_dir / "run_hls.tcl",
        out_dir / "run_csim.tcl",
        out_dir / "run_csynth.tcl",
        out_dir / "run_cosim.tcl",
        out_dir / "Makefile",
        out_dir / "run_all.sh",
    ]
    (out_dir / "src" / "hls_top.hpp").write_text(generated.header, encoding="utf-8")
    (out_dir / "src" / "hls_top.cpp").write_text(generated.source, encoding="utf-8")
    files.extend(
        _stage_generated_header_dependencies(
            out_dir,
            analysis.function.source_path,
            generated.header,
            list(getattr(config, "include_dirs", [])),
        )
    )
    (out_dir / "tb" / "testbench.cpp").write_text(generate_testbench(analysis, config), encoding="utf-8")
    (out_dir / "tb" / "leveri_golden_tb.cpp").write_text(leveri_bundle.golden_tb, encoding="utf-8")
    (out_dir / "tb" / "leveri_hls_tb.cpp").write_text(leveri_bundle.hls_tb, encoding="utf-8")
    (out_dir / "tb" / "leveri_compare.py").write_text(leveri_bundle.compare_script, encoding="utf-8")
    (out_dir / "tb" / "run_gcov.py").write_text(leveri_bundle.gcov_script, encoding="utf-8")
    (out_dir / "tb" / "klee_driver.cpp").write_text(leveri_bundle.klee_driver, encoding="utf-8")
    (out_dir / "tb" / "run_klee.py").write_text(leveri_bundle.klee_script, encoding="utf-8")
    (out_dir / "tb" / "leveri_manifest.json").write_text(leveri_bundle.manifest_json, encoding="utf-8")
    (out_dir / "tb" / "rtl_vectors_tb.cpp").write_text(verilog_bundle.vectors_tb, encoding="utf-8")
    (out_dir / "tb" / "gen_rtl_tb.py").write_text(verilog_bundle.gen_script, encoding="utf-8")
    (out_dir / "tb" / "run_rtl_sim.py").write_text(verilog_bundle.run_script, encoding="utf-8")
    (out_dir / "tb" / "rtl_tb_manifest.json").write_text(verilog_bundle.manifest_json, encoding="utf-8")
    (out_dir / "run_hls.tcl").write_text(render_run_hls(analysis, config), encoding="utf-8")
    (out_dir / "run_csim.tcl").write_text(render_run_csim(analysis, config), encoding="utf-8")
    (out_dir / "run_csynth.tcl").write_text(render_run_csynth(), encoding="utf-8")
    (out_dir / "run_cosim.tcl").write_text(render_run_cosim(config), encoding="utf-8")
    (out_dir / "Makefile").write_text(render_makefile(config), encoding="utf-8")
    run_all = out_dir / "run_all.sh"
    run_all.write_text(render_run_all(), encoding="utf-8")
    run_all.chmod(run_all.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    leveri_compare = out_dir / "tb" / "leveri_compare.py"
    leveri_compare.chmod(leveri_compare.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    for script_name in ("run_gcov.py", "run_klee.py", "gen_rtl_tb.py", "run_rtl_sim.py"):
        script = out_dir / "tb" / script_name
        script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return ProjectFiles(out_dir, files)
