from __future__ import annotations

import os
import shutil
import stat
from dataclasses import dataclass
from pathlib import Path

from .analyze import AnalysisResult
from .config import AgentConfig
from .convert import GeneratedSource
from .testgen import generate_testbench


@dataclass
class ProjectFiles:
    root: Path
    generated_files: list[Path]


def render_run_hls(analysis: AnalysisResult, config: AgentConfig) -> str:
    fn = analysis.function
    cosim = f"cosim_design -rtl {config.rtl}"
    if config.cosim_tool:
        cosim = f"cosim_design -tool {config.cosim_tool} -rtl {config.rtl}"
    return f"""# Generated by c2hlsc_agent.
open_project c2hlsc_project
set_top {fn.name}
add_files src/hls_top.cpp
add_files -tb tb/testbench.cpp
open_solution "solution1" -flow_target vivado
set_part {{{config.part}}}
create_clock -period {config.clock} -name default
csim_design
csynth_design
{cosim}
exit
"""


def render_makefile(config: AgentConfig) -> str:
    flags = " ".join(config.compiler_flags)
    return f"""CXX ?= g++
CXXFLAGS ?= -std=c++17 -Wall -Wextra -I src {flags}
TB_EXE ?= c2hlsc_tb

.PHONY: all test clean vitis

all: test

$(TB_EXE): tb/testbench.cpp src/hls_top.cpp src/hls_top.hpp input.c
\t$(CXX) $(CXXFLAGS) tb/testbench.cpp src/hls_top.cpp -o $(TB_EXE)

test: $(TB_EXE)
\t./$(TB_EXE)

vitis:
\tvitis_hls -f run_hls.tcl

clean:
\trm -f $(TB_EXE)
\trm -rf c2hlsc_project
"""


def render_run_all() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail
make test
if command -v vitis_hls >/dev/null 2>&1; then
  vitis_hls -f run_hls.tcl
else
  echo "vitis_hls not found; host equivalence completed, Vitis phases skipped." >&2
fi
"""


def write_project(out_dir: Path, analysis: AnalysisResult, generated: GeneratedSource, config: AgentConfig) -> ProjectFiles:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "src").mkdir(exist_ok=True)
    (out_dir / "tb").mkdir(exist_ok=True)
    shutil.copyfile(analysis.function.source_path, out_dir / "input.c")
    files = [
        out_dir / "input.c",
        out_dir / "src" / "hls_top.hpp",
        out_dir / "src" / "hls_top.cpp",
        out_dir / "tb" / "testbench.cpp",
        out_dir / "run_hls.tcl",
        out_dir / "Makefile",
        out_dir / "run_all.sh",
    ]
    (out_dir / "src" / "hls_top.hpp").write_text(generated.header, encoding="utf-8")
    (out_dir / "src" / "hls_top.cpp").write_text(generated.source, encoding="utf-8")
    (out_dir / "tb" / "testbench.cpp").write_text(generate_testbench(analysis, config), encoding="utf-8")
    (out_dir / "run_hls.tcl").write_text(render_run_hls(analysis, config), encoding="utf-8")
    (out_dir / "Makefile").write_text(render_makefile(config), encoding="utf-8")
    run_all = out_dir / "run_all.sh"
    run_all.write_text(render_run_all(), encoding="utf-8")
    run_all.chmod(run_all.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return ProjectFiles(out_dir, files)
