from __future__ import annotations

import os
import shutil
import stat
from dataclasses import dataclass
from pathlib import Path

from .analyze import AnalysisResult
from .config import AgentConfig
from .convert import GeneratedSource
from .leveri_testgen import generate_leveri_testbenches
from .testgen import generate_testbench


@dataclass
class ProjectFiles:
    root: Path
    generated_files: list[Path]


def render_run_hls(analysis: AnalysisResult, config: AgentConfig) -> str:
    fn = analysis.function
    cosim = f"cosim_design -rtl {config.rtl}"
    if config.cosim_tool:
        cosim = f"cosim_design -tool {config.cosim_tool} -rtl {config.rtl}"
    return f"""# Generated by c2hlsc_agent.
open_project c2hlsc_project
set_top {fn.name}
add_files src/hls_top.cpp
add_files -tb tb/testbench.cpp
open_solution "solution1" -flow_target vivado
set_part {{{config.part}}}
create_clock -period {config.clock} -name default
csim_design
csynth_design
{cosim}
exit
"""


def render_run_csim(analysis: AnalysisResult, config: AgentConfig) -> str:
    fn = analysis.function
    return f"""# Generated by c2hlsc_agent.
open_project -reset c2hlsc_project
set_top {fn.name}
add_files src/hls_top.cpp
add_files -tb tb/testbench.cpp
open_solution "solution1" -flow_target vivado
set_part {{{config.part}}}
create_clock -period {config.clock} -name default
csim_design
exit
"""


def render_run_csynth() -> str:
    return """# Generated by c2hlsc_agent.
open_project c2hlsc_project
open_solution "solution1"
csynth_design
exit
"""


def render_run_cosim(config: AgentConfig) -> str:
    cosim = f"cosim_design -rtl {config.rtl}"
    if config.cosim_tool:
        cosim = f"cosim_design -tool {config.cosim_tool} -rtl {config.rtl}"
    return f"""# Generated by c2hlsc_agent.
open_project c2hlsc_project
open_solution "solution1"
{cosim}
exit
"""


def render_makefile(config: AgentConfig) -> str:
    flags = " ".join(config.compiler_flags)
    return f"""CXX ?= g++
CXXFLAGS ?= -std=c++17 -Wall -Wextra -I src {flags}
TB_EXE ?= c2hlsc_tb
LEVERI_GOLDEN_EXE ?= leveri_golden_tb
LEVERI_HLS_EXE ?= leveri_hls_tb

.PHONY: all test leveri-test gcov-coverage klee-coverage coverage clean vitis

all: test

$(TB_EXE): tb/testbench.cpp src/hls_top.cpp src/hls_top.hpp input.c
\t$(CXX) $(CXXFLAGS) tb/testbench.cpp src/hls_top.cpp -o $(TB_EXE)

$(LEVERI_GOLDEN_EXE): tb/leveri_golden_tb.cpp input.c
\t$(CXX) $(CXXFLAGS) tb/leveri_golden_tb.cpp -o $(LEVERI_GOLDEN_EXE)

$(LEVERI_HLS_EXE): tb/leveri_hls_tb.cpp src/hls_top.cpp src/hls_top.hpp
\t$(CXX) $(CXXFLAGS) tb/leveri_hls_tb.cpp src/hls_top.cpp -o $(LEVERI_HLS_EXE)

test: $(TB_EXE)
\t./$(TB_EXE)

leveri-test: $(LEVERI_GOLDEN_EXE) $(LEVERI_HLS_EXE)
\t./$(LEVERI_GOLDEN_EXE)
\t./$(LEVERI_HLS_EXE)
\tpython3 tb/leveri_compare.py leveri_golden_trace.csv leveri_hls_trace.csv

gcov-coverage:
\tpython3 tb/run_gcov.py

klee-coverage:
\tpython3 tb/run_klee.py

coverage: gcov-coverage klee-coverage

vitis:
\tvitis_hls -f run_hls.tcl

clean:
\trm -f $(TB_EXE) $(LEVERI_GOLDEN_EXE) $(LEVERI_HLS_EXE)
\trm -f leveri_golden_trace.csv leveri_hls_trace.csv
\trm -rf coverage
\trm -f *.gcda *.gcno *.gcov
\trm -rf c2hlsc_project
"""


def render_run_all() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail
make test
if command -v vitis_hls >/dev/null 2>&1; then
  vitis_hls -f run_hls.tcl
else
  echo "vitis_hls not found; host equivalence completed, Vitis phases skipped." >&2
fi
"""


def write_project(out_dir: Path, analysis: AnalysisResult, generated: GeneratedSource, config: AgentConfig) -> ProjectFiles:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "src").mkdir(exist_ok=True)
    (out_dir / "tb").mkdir(exist_ok=True)
    leveri_bundle = generate_leveri_testbenches(analysis, config)
    shutil.copyfile(analysis.function.source_path, out_dir / "input.c")
    files = [
        out_dir / "input.c",
        out_dir / "src" / "hls_top.hpp",
        out_dir / "src" / "hls_top.cpp",
        out_dir / "tb" / "testbench.cpp",
        out_dir / "tb" / "leveri_golden_tb.cpp",
        out_dir / "tb" / "leveri_hls_tb.cpp",
        out_dir / "tb" / "leveri_compare.py",
        out_dir / "tb" / "run_gcov.py",
        out_dir / "tb" / "klee_driver.cpp",
        out_dir / "tb" / "run_klee.py",
        out_dir / "tb" / "leveri_manifest.json",
        out_dir / "run_hls.tcl",
        out_dir / "run_csim.tcl",
        out_dir / "run_csynth.tcl",
        out_dir / "run_cosim.tcl",
        out_dir / "Makefile",
        out_dir / "run_all.sh",
    ]
    (out_dir / "src" / "hls_top.hpp").write_text(generated.header, encoding="utf-8")
    (out_dir / "src" / "hls_top.cpp").write_text(generated.source, encoding="utf-8")
    (out_dir / "tb" / "testbench.cpp").write_text(generate_testbench(analysis, config), encoding="utf-8")
    (out_dir / "tb" / "leveri_golden_tb.cpp").write_text(leveri_bundle.golden_tb, encoding="utf-8")
    (out_dir / "tb" / "leveri_hls_tb.cpp").write_text(leveri_bundle.hls_tb, encoding="utf-8")
    (out_dir / "tb" / "leveri_compare.py").write_text(leveri_bundle.compare_script, encoding="utf-8")
    (out_dir / "tb" / "run_gcov.py").write_text(leveri_bundle.gcov_script, encoding="utf-8")
    (out_dir / "tb" / "klee_driver.cpp").write_text(leveri_bundle.klee_driver, encoding="utf-8")
    (out_dir / "tb" / "run_klee.py").write_text(leveri_bundle.klee_script, encoding="utf-8")
    (out_dir / "tb" / "leveri_manifest.json").write_text(leveri_bundle.manifest_json, encoding="utf-8")
    (out_dir / "run_hls.tcl").write_text(render_run_hls(analysis, config), encoding="utf-8")
    (out_dir / "run_csim.tcl").write_text(render_run_csim(analysis, config), encoding="utf-8")
    (out_dir / "run_csynth.tcl").write_text(render_run_csynth(), encoding="utf-8")
    (out_dir / "run_cosim.tcl").write_text(render_run_cosim(config), encoding="utf-8")
    (out_dir / "Makefile").write_text(render_makefile(config), encoding="utf-8")
    run_all = out_dir / "run_all.sh"
    run_all.write_text(render_run_all(), encoding="utf-8")
    run_all.chmod(run_all.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    leveri_compare = out_dir / "tb" / "leveri_compare.py"
    leveri_compare.chmod(leveri_compare.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    for script_name in ("run_gcov.py", "run_klee.py"):
        script = out_dir / "tb" / script_name
        script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return ProjectFiles(out_dir, files)
