"""Local synthesis + waveform + STA step: yosys -> gate netlist -> OpenSTA slack/power.

Generalizes the ``build/cnn_3x3/syn`` reference flow (see its ``run_ppa.sh``) into a
per-project step the QoR optimizer can run after Vitis csynth:

1. **Synthesis** — yosys maps the Vitis-generated RTL to the target liberty (Nangate45
   by default), writing ``syn/yosys_area.rpt`` (std-cell area) and a gate netlist.
2. **Gate-level waveform sim** (best-effort) — when the project carries the
   self-checking RTL testbench artifacts (``tb/<top>_tb.sv`` + ``rtl_vectors/``) and
   Icarus Verilog is installed, the netlist is simulated against the golden vectors with
   liberty-derived cell models, dumping ``waves/<top>_gate.vcd`` for inspection.
3. **STA** — OpenSTA reports worst setup/hold slack, TNS, and power into
   ``syn/sta_report.txt``.

The report paths match :func:`c2hlsc_agent.qor.collect_local_ppa`, so the parsed area /
slack / power land directly in the QoR metrics that drive PPA-target checking.

Everything runs locally on the Mac; only the Vitis phases ever leave the machine.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from .qor import QoRMetrics, collect_local_ppa

_DEFAULT_STA_CANDIDATES = (
    os.environ.get("STA_BIN", ""),
    os.environ.get("C2HLSC_STA", ""),
    str(Path.home() / "tools" / "eda" / "opensta" / "bin" / "sta"),
)


@dataclass
class LocalPPAOutcome:
    status: str  # "ok" | "skipped" | "fail"
    note: str = ""
    netlist: str | None = None
    gate_sim: str = "skipped"  # "pass" | "fail" | "skipped"
    gate_sim_note: str = ""
    vcd: str | None = None
    reports: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "note": self.note,
            "netlist": self.netlist,
            "gate_sim": self.gate_sim,
            "gate_sim_note": self.gate_sim_note,
            "vcd": self.vcd,
            "reports": list(self.reports),
        }


def resolve_sta_bin(explicit: str | None = None) -> str | None:
    if explicit:
        return explicit
    for candidate in _DEFAULT_STA_CANDIDATES:
        if candidate and Path(candidate).exists():
            return candidate
    return shutil.which("sta")


def resolve_liberty(project_dir: Path, explicit: str | None = None) -> Path | None:
    if explicit:
        path = Path(explicit).expanduser()
        return path if path.exists() else None
    env = os.environ.get("C2HLSC_LIBERTY")
    if env and Path(env).expanduser().exists():
        return Path(env).expanduser()
    local = sorted((project_dir / "syn" / "lib").glob("*.lib"))
    if local:
        return local[0]
    return None


def find_rtl_sources(project_dir: Path) -> list[Path]:
    """Vitis-generated RTL first (remote pull brings it back), then an ``rtl/`` copy."""

    env_dir = os.environ.get("C2HLSC_RTL_DIR")
    if env_dir and Path(env_dir).is_dir():
        return sorted(Path(env_dir).glob("*.v"))
    vitis = sorted((project_dir / "c2hlsc_project" / "solution1" / "syn" / "verilog").glob("*.v"))
    if vitis:
        return vitis
    return sorted((project_dir / "rtl").glob("*.v"))


def _yosys_script(rtl: list[Path], top: str, liberty: Path, clock_ns: float, netlist: Path) -> str:
    reads = "\n".join(f"read_verilog {path.as_posix()}" for path in rtl)
    delay_ps = int(clock_ns * 1000)
    liberty_path = liberty.as_posix()
    netlist_path = netlist.as_posix()
    return f"""# Generated by c2hlsc_agent local_ppa: {top} -> gate netlist + area report
{reads}
hierarchy -check -top {top}
synth -top {top}
dfflibmap -liberty {liberty_path}
abc -liberty {liberty_path} -D {delay_ps}
opt_clean -purge
tee -o syn/yosys_check.rpt check
tee -o syn/yosys_area.rpt stat -liberty {liberty_path}
write_verilog -noattr -noexpr {netlist_path}
"""


def _netlist_input_ports(netlist: Path, clock_port: str) -> list[str]:
    """Input port names (bus base names) of the top module in a yosys-written netlist,
    excluding the clock. Needed because this OpenSTA build has no collection ops
    (``remove_from_collection``/``foreach_in_collection``) — ports must be explicit,
    exactly like the reference ``sta_cnn3x3.tcl``."""

    text = netlist.read_text(encoding="utf-8", errors="replace")
    ports = re.findall(r"^\s*input\s+(?:\[[^\]]+\]\s*)?(\\?\w+)\s*;", text, re.M)
    return [p for p in dict.fromkeys(ports) if p != clock_port]


def _sta_script(
    liberty: Path,
    netlist: Path,
    top: str,
    clock_ns: float,
    clock_port: str,
    input_ports: list[str] | None = None,
) -> str:
    inputs = " ".join(input_ports or [])
    liberty_path = liberty.as_posix()
    netlist_path = netlist.as_posix()
    input_delay = (
        f"set_input_delay 2.0 -clock {clock_port} [get_ports {{{inputs}}}]" if inputs else "# no non-clock inputs"
    )
    return f"""# Generated by c2hlsc_agent local_ppa: timing + power on the mapped netlist
read_liberty {liberty_path}
read_verilog {netlist_path}
link_design {top}

create_clock -name {clock_port} -period {clock_ns} [get_ports {clock_port}]
set_clock_uncertainty -setup 0.1 [get_clocks {clock_port}]
set_clock_uncertainty -hold 0.05 [get_clocks {clock_port}]
{input_delay}
set_output_delay 2.0 -clock {clock_port} [all_outputs]
set_load 0.02 [all_outputs]

puts "==== WORST SETUP (max) PATHS ===="
report_checks -path_delay max -fields {{slew cap input_pins}} -digits 3 -group_path_count 3
puts "==== WORST HOLD (min) PATH ===="
report_checks -path_delay min -digits 3
puts "==== SLACK SUMMARY ===="
report_worst_slack -max
report_worst_slack -min
report_tns
puts "==== POWER (typical corner, default activity) ===="
report_power
"""


# ---------------------------------------------------------------------------- #
# Liberty-driven functional cell models (ported from build/cnn_3x3/syn/gen_cell_models.py)
# ---------------------------------------------------------------------------- #


def _cells_in_netlist(netlist: Path) -> list[str]:
    text = netlist.read_text(encoding="utf-8", errors="replace")
    return sorted(set(re.findall(r"^\s*([A-Z][A-Z0-9_]*_X\d+)\s+\S+\s*\(", text, re.M)))


def _liberty_cell_blocks(liberty: Path) -> dict[str, str]:
    text = liberty.read_text(encoding="utf-8", errors="replace")
    blocks: dict[str, str] = {}
    for match in re.finditer(r"\bcell\s*\(\s*([A-Za-z0-9_]+)\s*\)\s*\{", text):
        name, depth, i = match.group(1), 1, match.end()
        while depth and i < len(text):
            depth += text[i] == "{"
            depth -= text[i] == "}"
            i += 1
        blocks[name] = text[match.end() : i - 1]
    return blocks


def _parse_pins(block: str) -> list[tuple[str, str, str | None]]:
    pins: list[tuple[str, str, str | None]] = []
    for match in re.finditer(r"\bpin\s*\(\s*([A-Za-z0-9_]+)\s*\)\s*\{", block):
        name, depth, i = match.group(1), 1, match.end()
        while depth and i < len(block):
            depth += block[i] == "{"
            depth -= block[i] == "}"
            i += 1
        body = block[match.end() : i - 1]
        direction = re.search(r"direction\s*:\s*(\w+)", body)
        function = re.search(r'function\s*:\s*"([^"]*)"', body)
        pins.append((name, direction.group(1) if direction else "input", function.group(1) if function else None))
    return pins


def _liberty_expr_to_verilog(expr: str) -> str:
    """Liberty boolean expression -> Verilog. Handles postfix ``'`` negation (innermost
    first), ``!``, ``*``, ``+``; raises on any operator this translation cannot model."""

    prev = None
    while prev != expr:
        prev = expr
        expr = re.sub(r"([A-Za-z0-9_]+|\))\s*'", r"~\1", expr)
    expr = expr.replace("!", "~").replace("*", "&").replace("+", "|")
    unhandled = re.sub(r"[A-Za-z0-9_\s()~&|^]", "", expr)
    if unhandled:
        raise ValueError(f"unhandled liberty operators {unhandled!r} in {expr!r}")
    return re.sub(r"\s+", " ", expr).strip()


def _ff_group(block: str) -> tuple[str, str, str, str] | None:
    """Return ``(state, state_n, next_state, clocked_on)`` from the liberty ``ff`` group."""

    match = re.search(r'ff\s*\(\s*"?(\w+)"?\s*,\s*"?(\w+)"?\s*\)\s*\{([^}]*)\}', block)
    if not match:
        return None
    body = match.group(3)
    next_state = re.search(r'next_state\s*:\s*"([^"]*)"', body)
    clocked_on = re.search(r'clocked_on\s*:\s*"([^"]*)"', body)
    if not next_state or not clocked_on:
        return None
    return match.group(1), match.group(2), next_state.group(1), clocked_on.group(1)


def generate_cell_models(liberty: Path, netlist: Path, out_path: Path) -> int:
    """Emit iverilog functional models for the liberty cells the netlist instantiates.

    Faithful port of ``build/cnn_3x3/syn/gen_cell_models.py``: combinational functions
    come verbatim from the liberty ``function`` attribute; flip-flops model the internal
    state (``reg IQ``) with ``Q = IQ`` / ``QN = ~IQ`` output mapping so inverted outputs
    keep the right polarity. Cells this translation cannot model are skipped (the gate
    sim then fails to compile, which is reported — never silently mis-modeled).
    Returns the number of modeled cells.
    """

    used = _cells_in_netlist(netlist)
    blocks = _liberty_cell_blocks(liberty)
    modules: list[str] = [
        "// Auto-generated liberty functional models (c2hlsc_agent local_ppa)",
        "`timescale 1ns/1ps",
    ]
    modeled = 0
    for cell in used:
        block = blocks.get(cell)
        if block is None:
            continue
        pins = _parse_pins(block)
        inputs = [name for name, direction, _fn in pins if direction == "input"]
        outputs = [(name, fn) for name, direction, fn in pins if direction == "output"]
        ports = ", ".join([name for name, _fn in outputs] + inputs)
        lines = [f"module {cell}({ports});"]
        for name in inputs:
            lines.append(f"  input {name};")
        for name, _fn in outputs:
            lines.append(f"  output {name};")
        ff = _ff_group(block)
        try:
            if ff:
                state, state_n, next_state, clocked_on = ff
                lines.append(f"  reg {state};")
                lines.append(
                    f"  always @(posedge ({_liberty_expr_to_verilog(clocked_on)})) "
                    f"{state} <= {_liberty_expr_to_verilog(next_state)};"
                )
                for name, fn in outputs:
                    target = {state: state, state_n: f"~{state}"}.get((fn or "").strip())
                    if target is None:
                        raise ValueError(f"{cell}: unsupported ff output function {fn!r}")
                    lines.append(f"  assign {name} = {target};")
            else:
                for name, fn in outputs:
                    if fn is None:
                        raise ValueError(f"{cell}: output {name} has no function")
                    lines.append(f"  assign {name} = {_liberty_expr_to_verilog(fn)};")
        except ValueError:
            continue  # skip unmodelable cell; a compile error will surface it loudly
        lines.append("endmodule")
        modules.append("\n".join(lines))
        modeled += 1
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n\n".join(modules) + "\n", encoding="utf-8")
    return modeled


def _run(cmd: list[str], cwd: Path, timeout: int) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)


def _gate_waveform_sim(
    project_dir: Path, top: str, liberty: Path, netlist: Path, outcome: LocalPPAOutcome
) -> None:
    """Best-effort gate-level sim of the netlist against the golden RTL testbench,
    dumping ``waves/<top>_gate.vcd``. Requires the RTL-TB artifacts + iverilog."""

    tb = project_dir / "tb" / f"{top}_tb.sv"
    vectors = project_dir / "rtl_vectors"
    if not tb.exists() or not vectors.is_dir():
        outcome.gate_sim_note = "skipped: RTL testbench artifacts missing (run tb/run_rtl_sim.py first)"
        return
    if shutil.which("iverilog") is None or shutil.which("vvp") is None:
        outcome.gate_sim_note = "skipped: iverilog/vvp not installed"
        return
    models = project_dir / "syn" / "lib" / "cells_sim.v"
    try:
        generate_cell_models(liberty, netlist, models)
    except OSError as exc:
        outcome.gate_sim_note = f"skipped: cell-model generation failed ({exc})"
        return
    waves = project_dir / "waves"
    waves.mkdir(exist_ok=True)
    vcd = waves / f"{top}_gate.vcd"
    dump = waves / "dump_gate.v"
    dump.write_text(
        f'module dump_gate; initial begin $dumpfile("{vcd}"); $dumpvars; end endmodule\n',
        encoding="utf-8",
    )
    sim = project_dir / "syn" / "sim_gate"
    try:
        compile_proc = _run(
            ["iverilog", "-g2012", "-o", str(sim), str(tb), str(netlist), str(models), str(dump)],
            project_dir,
            timeout=300,
        )
        if compile_proc.returncode != 0:
            outcome.gate_sim = "fail"
            outcome.gate_sim_note = f"iverilog: {compile_proc.stderr.strip()[-300:]}"
            return
        run_proc = _run(["vvp", str(sim)], project_dir, timeout=600)
    except (subprocess.TimeoutExpired, OSError) as exc:
        outcome.gate_sim = "fail"
        outcome.gate_sim_note = f"gate sim did not complete: {exc}"
        return
    text = run_proc.stdout + run_proc.stderr
    # Match the canonical self-checking-TB markers (same contract as tb/run_rtl_sim.py):
    # a run only passes when the TB explicitly says so.
    failed = run_proc.returncode != 0 or "RTL_TB: FAIL" in text or "RTL_TB: MISMATCH" in text
    passed = not failed and "RTL_TB: PASS" in text
    outcome.gate_sim = "pass" if passed else "fail"
    verdict_line = next((l for l in text.splitlines() if "RTL_TB:" in l), None)
    outcome.gate_sim_note = (verdict_line or (text.strip().splitlines() or [""])[-1])[:200]
    outcome.vcd = str(vcd) if vcd.exists() else None


def run_local_ppa(
    project_dir: Path,
    top: str,
    clock_ns: float,
    liberty: str | None = None,
    sta_bin: str | None = None,
    clock_port: str = "ap_clk",
    gate_sim: bool = True,
    metrics: QoRMetrics | None = None,
    verbose: bool = False,
) -> tuple[QoRMetrics | None, LocalPPAOutcome]:
    """Synthesis + (waveform sim) + STA on the project's RTL; returns enriched metrics.

    Returns ``(metrics, outcome)`` — metrics is ``None`` only when the flow could not
    run at all (missing RTL/liberty/tools); the outcome always says why.
    """

    outcome = LocalPPAOutcome(status="skipped")
    rtl = find_rtl_sources(project_dir)
    if not rtl:
        outcome.note = "no RTL found (run csynth first; remote runs pull syn/verilog back)"
        return None, outcome
    lib = resolve_liberty(project_dir, liberty)
    if lib is None:
        outcome.note = "no liberty file (pass --liberty, set C2HLSC_LIBERTY, or add syn/lib/*.lib)"
        return None, outcome
    if shutil.which("yosys") is None:
        outcome.note = "yosys not installed"
        return None, outcome
    sta = resolve_sta_bin(sta_bin)

    syn_dir = project_dir / "syn"
    syn_dir.mkdir(exist_ok=True)
    # Remove previous reports up front: if a tool fails mid-flow, collect_local_ppa must
    # never parse a stale report from an earlier design revision as if it were current.
    for stale in ("yosys_area.rpt", "sta_report.txt"):
        (syn_dir / stale).unlink(missing_ok=True)
    netlist = syn_dir / f"{top}_netlist.v"
    (syn_dir / "synth_gen.ys").write_text(_yosys_script(rtl, top, lib, clock_ns, netlist), encoding="utf-8")
    try:
        yosys_proc = _run(["yosys", "-q", "-s", str(syn_dir / "synth_gen.ys")], project_dir, timeout=1800)
    except (subprocess.TimeoutExpired, OSError) as exc:
        outcome.status = "fail"
        outcome.note = f"yosys did not complete: {exc}"
        return None, outcome
    if yosys_proc.returncode != 0 or not netlist.exists():
        outcome.status = "fail"
        outcome.note = f"yosys failed: {yosys_proc.stderr.strip()[-300:]}"
        return None, outcome
    outcome.netlist = str(netlist)
    outcome.reports.append(str(syn_dir / "yosys_area.rpt"))

    if gate_sim:
        _gate_waveform_sim(project_dir, top, lib, netlist, outcome)
        if verbose and outcome.gate_sim != "skipped":
            print(f"gate-level waveform sim: {outcome.gate_sim} ({outcome.gate_sim_note})")

    if sta is None:
        outcome.status = "ok"
        outcome.note = "yosys area only; OpenSTA not found (pass --sta-bin or set STA_BIN) — no slack/power"
    else:
        (syn_dir / "sta_gen.tcl").write_text(
            _sta_script(lib, netlist, top, clock_ns, clock_port, _netlist_input_ports(netlist, clock_port)),
            encoding="utf-8",
        )
        try:
            sta_proc = _run([sta, "-no_splash", "-exit", str(syn_dir / "sta_gen.tcl")], project_dir, timeout=900)
        except (subprocess.TimeoutExpired, OSError) as exc:
            outcome.status = "fail"
            outcome.note = f"OpenSTA did not complete: {exc}"
            sta_proc = None
        if sta_proc is not None:
            sta_text = sta_proc.stdout + sta_proc.stderr
            (syn_dir / "sta_report.txt").write_text(sta_text, encoding="utf-8")
            outcome.reports.append(str(syn_dir / "sta_report.txt"))
            # This OpenSTA build can exit 0 after a Tcl error; scan for Error lines too.
            error_line = re.search(r"^Error[: ].*$", sta_text, re.M)
            if sta_proc.returncode != 0 or error_line:
                outcome.status = "fail"
                outcome.note = f"OpenSTA failed: {(error_line.group(0) if error_line else sta_proc.stderr.strip())[-300:]}"
                # Do not let a failed STA's partial report be parsed as measurements.
                (syn_dir / "sta_report.txt").rename(syn_dir / "sta_report.failed.txt")
            else:
                outcome.status = "ok"

    metrics = metrics or QoRMetrics()
    collect_local_ppa(project_dir, metrics)
    return metrics, outcome
