from __future__ import annotations

from .analyze import AnalysisResult, FunctionArg
from .config import AgentConfig


def _is_unsigned(c_type: str) -> bool:
    return "unsigned" in c_type or c_type.strip().startswith("uint") or "ap_uint" in c_type


def _scalar_decl(arg: FunctionArg) -> str:
    if arg.scalar_range:
        lo, hi = arg.scalar_range
        return f"static_cast<{arg.c_type}>({lo} + (rng() % ({hi} - {lo} + 1)))"
    return f"random_value<{arg.c_type}>(rng)"


def _storage_type(arg: FunctionArg) -> str:
    return " ".join(token for token in arg.c_type.split() if token not in {"const", "volatile"})


def _value_print(expr: str) -> str:
    return f"static_cast<long long>({expr})"


def _init_array(arg: FunctionArg) -> str:
    unsigned = "true" if _is_unsigned(arg.c_type) else "false"
    return f"""for (int i = 0; i < {arg.length}; ++i) {{
      auto v = patterned_value<{_storage_type(arg)}>(test_idx, i, rng, {unsigned});
      ref_{arg.name}[i] = v;
      hls_{arg.name}[i] = v;
    }}"""


def _call_args(prefix: str, args: list[FunctionArg]) -> str:
    values: list[str] = []
    for arg in args:
        if arg.is_pointer_like:
            values.append(f"{prefix}_{arg.name}")
        else:
            values.append(arg.name)
    return ", ".join(values)


def generate_testbench(analysis: AnalysisResult, config: AgentConfig) -> str:
    fn = analysis.function
    arrays = [arg for arg in fn.args if arg.is_pointer_like]
    scalars = [arg for arg in fn.args if not arg.is_pointer_like]
    declarations: list[str] = []
    initializers: list[str] = []
    for arg in arrays:
        storage_type = _storage_type(arg)
        declarations.append(f"    {storage_type} ref_{arg.name}[{arg.length}] = {{}};")
        declarations.append(f"    {storage_type} hls_{arg.name}[{arg.length}] = {{}};")
        initializers.append("    " + _init_array(arg).replace("\n", "\n    "))
    for arg in scalars:
        declarations.append(f"    {arg.c_type} {arg.name} = {_scalar_decl(arg)};")

    return_compare = ""
    return_capture_ref = ""
    return_capture_hls = ""
    if fn.return_type != "void":
        return_capture_ref = f"{fn.return_type} ref_ret = "
        return_capture_hls = f"{fn.return_type} hls_ret = "
        return_compare = f"""
    if (ref_ret != hls_ret) {{
      std::cerr << "Mismatch test=" << test_idx << " return expected="
                << {_value_print('ref_ret')} << " actual=" << {_value_print('hls_ret')}
                << " seed={config.seed}\\n";
      return 1;
    }}"""

    comparisons: list[str] = []
    for arg in arrays:
        if arg.direction in {"output", "inout"}:
            comparisons.append(f"""    for (int i = 0; i < {arg.length}; ++i) {{
      if (ref_{arg.name}[i] != hls_{arg.name}[i]) {{
        std::cerr << "Mismatch test=" << test_idx << " arg={arg.name} index=" << i
                  << " expected=" << {_value_print(f'ref_{arg.name}[i]')}
                  << " actual=" << {_value_print(f'hls_{arg.name}[i]')}
                  << " seed={config.seed}\\n";
        return 1;
      }}
    }}""")

    return f"""// Generated by c2hlsc_agent. This file is testbench-only code.
#include <algorithm>
#include <cstdint>
#include <iostream>
#include <limits>
#include <random>

extern "C" {{
#define {fn.name} {fn.name}_ref
#include "../input.c"
#undef {fn.name}
}}

#include "../src/hls_top.hpp"

template <typename T>
T random_value(std::mt19937_64& rng) {{
  if constexpr (std::numeric_limits<T>::is_integer) {{
    return static_cast<T>(rng());
  }} else {{
    return static_cast<T>((rng() % 20001) - 10000) / static_cast<T>(100);
  }}
}}

template <typename T>
T patterned_value(int test_idx, int element_idx, std::mt19937_64& rng, bool is_unsigned) {{
  if (test_idx == 0) return static_cast<T>(0);
  if (test_idx == 1) return static_cast<T>(~static_cast<unsigned long long>(0));
  if (test_idx == 2 && std::numeric_limits<T>::is_integer) {{
    return is_unsigned ? std::numeric_limits<T>::max()
                       : (element_idx % 2 ? std::numeric_limits<T>::max() : std::numeric_limits<T>::min());
  }}
  if (test_idx == 3) return static_cast<T>(element_idx % 2 ? 0xAAAAAAAAULL : 0x55555555ULL);
  return random_value<T>(rng);
}}

int main() {{
  std::mt19937_64 rng({config.seed}ULL);
  for (int test_idx = 0; test_idx < {config.num_tests}; ++test_idx) {{
{chr(10).join(declarations)}
{chr(10).join(initializers)}

    {return_capture_ref}{fn.name}_ref({_call_args('ref', fn.args)});
    {return_capture_hls}{fn.name}({_call_args('hls', fn.args)});
{return_compare}
{chr(10).join(comparisons)}
  }}
  std::cout << "c2hlsc_agent: all {config.num_tests} tests passed, seed={config.seed}\\n";
  return 0;
}}
"""
